global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    cluster: 'porch'
    environment: 'testing'

scrape_configs:
  - job_name: 'porch-server'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['api.porch-system.svc.cluster.local:9464']
        labels:
          service: 'porch-server'
          component: 'apiserver'

  - job_name: 'function-runner'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['function-runner.porch-system.svc.cluster.local:9464']
        labels:
          service: 'function-runner'
          component: 'grpc-server'

  - job_name: 'porch-performance-tests'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: [ '172.17.0.1:9095' ]
        labels:
          service: 'porch-perf-test'
