---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: porch-controllers-fleetsyncs
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - fleetmembershipbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - fleetmemberships
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - fleetscopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - fleetsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - fleetsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - fleetsyncs/status
  verbs:
  - get
  - patch
  - update
