apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: insert-metrics-scraping
  namespace: porch-system
source: |
  for resource in ctx.resource_list["items"]:
    if resource["apiVersion"] != "v1" or resource["kind"] != "Service":
      continue
    resource["metadata"]["annotations"]["prometheus.io/scrape"] = "true"
    resource["metadata"]["annotations"]["prometheus.io/port"] = "9464"
    resource["metadata"]["annotations"]["prometheus.io/path"] = "/metrics"