kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: management
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 31000
  podSubnet: 10.97.0.0/16
  serviceSubnet: 10.197.0.0/16
nodes:
- role: control-plane
  image: kindest/node:v1.32.2
  extraPortMappings:
  - containerPort: 30000 # Gitea NodePort
    hostPort: 3000
  - containerPort: 30001 # function-runner NodePort
    hostPort: 30001
