kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: management
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 31000
  podSubnet: 10.97.0.0/16
  serviceSubnet: 10.197.0.0/16
nodes:
- role: control-plane
  image: kindest/node:v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiVersion: kubeadm.k8s.io/v1beta3
    apiServer:
      extraArgs:
        request-timeout: "300s"
  extraPortMappings:
  - containerPort: 30000 # Gitea NodePort
    hostPort: 3000
  - containerPort: 30001 # function-runner NodePort
    hostPort: 30001
  - containerPort: 30002 # Porch postgres NodePort
    hostPort: 5432
  extraMounts:
    - containerPath: /mnt/postgresql
      hostPath: /tmp/porch/postgresql
