apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: insert-db-cache-config
source: |    
    for resource in ctx.resource_list["items"]:
      containers = resource.get("spec", {}).get("template", {}).get("spec", {}).get("containers", [])
      for container in containers:
        if "envFrom" not in container:
            container["envFrom"] = []

        existing = []
        for e in container["envFrom"]:
            for k, v in e.items():
                existing.append((k, v))

        inserts = [
            ("configMapRef", {"name": "porch-db-config"}),
            ("secretRef", {"name": "porch-db-secret"}),
        ]

        for key, value in inserts:
            if (key, value) not in existing:
                container["envFrom"].append({key: value})

        cache_type = "--cache-type=db"

        if cache_type not in container["args"]:
            container["args"].append(cache_type)
