template: testify
template-data:
  unroll-variadic: true
filename: "mock_{{ .InterfaceName }}.go"
dir: "test/mockery/mocks/porch/{{.InterfaceDirRelative}}"

packages:
  sigs.k8s.io/controller-runtime/pkg/client:
    interfaces:
      Client:
        config:
          dir: "test/mockery/mocks/external/sigs.k8s.io/controller-runtime/pkg/client"
      Reader:
        config:
          dir: "test/mockery/mocks/external/sigs.k8s.io/controller-runtime/pkg/client"
      SubResourceWriter:
        config:
          dir: "test/mockery/mocks/external/sigs.k8s.io/controller-runtime/pkg/client"
      WithWatch:
        config:
          dir: "test/mockery/mocks/external/sigs.k8s.io/controller-runtime/pkg/client"

  github.com/nephio-project/porch/pkg/cache/crcache/meta:
    interfaces:
      MetadataStore: {}

  github.com/nephio-project/porch/pkg/cache/dbcache:
    interfaces:
      dbSQLInterface:
        config:
          structname: "MockdbSQLInterface"

  github.com/nephio-project/porch/pkg/cache/types:
    interfaces:
      Cache: {}
      RepoPRChangeNotifier: {}

  github.com/nephio-project/porch/pkg/repository:
    interfaces:
      Repository: {}
      PackageRevision: {}
      PackageRevisionDraft: {}

  github.com/nephio-project/porch/pkg/engine:
    interfaces:
      CaDEngine: {}
      WatcherManager: {}
