with-expecter: true
packages:
  sigs.k8s.io/controller-runtime/pkg/client:
    interfaces:
      Client:
        config:
          dir: "test/mockery/mocks/external/{{.InterfaceDirRelative}}"
          outpkg: "{{.PackageName}}"
      Reader:
        config:
          dir: "test/mockery/mocks/external/{{.InterfaceDirRelative}}"
          outpkg: "{{.PackageName}}"
  github.com/nephio-project/porch/pkg/repository:
    interfaces:
      Repository:
        config:
          dir: "test/mockery/mocks/porch/{{.InterfaceDirRelative}}"
          outpkg: "{{.PackageName}}"
  github.com/nephio-project/porch/pkg/cache/types:
    interfaces:
      RepoPRChangeNotifier:
        config:
          dir: "test/mockery/mocks/porch/{{.InterfaceDirRelative}}"
          outpkg: "{{.PackageName}}"
  github.com/nephio-project/porch/pkg/cache/crcache/meta:
    interfaces:
      MetadataStore:
        config:
          dir: "test/mockery/mocks/porch/{{.InterfaceDirRelative}}"
          outpkg: "{{.PackageName}}"
