presubmits:
  - name: presubmit-nephio-go-test
    decorate: true
    run_if_changed: "(\\.go|Makefile|\\.mk)$"
    spec:
      containers:
      - image: nephio/gotests:1782782171367346176
        command:
        - make
        args:
        - ci-unit
