presubmits:
  - name: presubmit-nephio-go-test
    decorate: true
    run_if_changed: "(\\.go|Makefile|\\.mk)$"
    spec:
      containers:
      - image: nephio/gotests:1919654500491071488
        command:
        - make
        args:
        - ci-unit
