// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/nephio-project/porch/pkg/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContentCache creates a new instance of MockContentCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentCache {
	mock := &MockContentCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentCache is an autogenerated mock type for the ContentCache type
type MockContentCache struct {
	mock.Mock
}

type MockContentCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentCache) EXPECT() *MockContentCache_Expecter {
	return &MockContentCache_Expecter{mock: &_m.Mock}
}

// CloseDraft provides a mock function for the type MockContentCache
func (_mock *MockContentCache) CloseDraft(ctx context.Context, repoKey repository.RepositoryKey, draft repository.PackageRevisionDraftSlim, version int) error {
	ret := _mock.Called(ctx, repoKey, draft, version)

	if len(ret) == 0 {
		panic("no return value specified for CloseDraft")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, repository.PackageRevisionDraftSlim, int) error); ok {
		r0 = returnFunc(ctx, repoKey, draft, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContentCache_CloseDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseDraft'
type MockContentCache_CloseDraft_Call struct {
	*mock.Call
}

// CloseDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - repoKey repository.RepositoryKey
//   - draft repository.PackageRevisionDraftSlim
//   - version int
func (_e *MockContentCache_Expecter) CloseDraft(ctx interface{}, repoKey interface{}, draft interface{}, version interface{}) *MockContentCache_CloseDraft_Call {
	return &MockContentCache_CloseDraft_Call{Call: _e.mock.On("CloseDraft", ctx, repoKey, draft, version)}
}

func (_c *MockContentCache_CloseDraft_Call) Run(run func(ctx context.Context, repoKey repository.RepositoryKey, draft repository.PackageRevisionDraftSlim, version int)) *MockContentCache_CloseDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RepositoryKey
		if args[1] != nil {
			arg1 = args[1].(repository.RepositoryKey)
		}
		var arg2 repository.PackageRevisionDraftSlim
		if args[2] != nil {
			arg2 = args[2].(repository.PackageRevisionDraftSlim)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContentCache_CloseDraft_Call) Return(err error) *MockContentCache_CloseDraft_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContentCache_CloseDraft_Call) RunAndReturn(run func(ctx context.Context, repoKey repository.RepositoryKey, draft repository.PackageRevisionDraftSlim, version int) error) *MockContentCache_CloseDraft_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDraftFromExisting provides a mock function for the type MockContentCache
func (_mock *MockContentCache) CreateDraftFromExisting(ctx context.Context, repoKey repository.RepositoryKey, pkgName string, workspace string) (repository.PackageRevisionDraftSlim, error) {
	ret := _mock.Called(ctx, repoKey, pkgName, workspace)

	if len(ret) == 0 {
		panic("no return value specified for CreateDraftFromExisting")
	}

	var r0 repository.PackageRevisionDraftSlim
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, string, string) (repository.PackageRevisionDraftSlim, error)); ok {
		return returnFunc(ctx, repoKey, pkgName, workspace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, string, string) repository.PackageRevisionDraftSlim); ok {
		r0 = returnFunc(ctx, repoKey, pkgName, workspace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PackageRevisionDraftSlim)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.RepositoryKey, string, string) error); ok {
		r1 = returnFunc(ctx, repoKey, pkgName, workspace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentCache_CreateDraftFromExisting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDraftFromExisting'
type MockContentCache_CreateDraftFromExisting_Call struct {
	*mock.Call
}

// CreateDraftFromExisting is a helper method to define mock.On call
//   - ctx context.Context
//   - repoKey repository.RepositoryKey
//   - pkgName string
//   - workspace string
func (_e *MockContentCache_Expecter) CreateDraftFromExisting(ctx interface{}, repoKey interface{}, pkgName interface{}, workspace interface{}) *MockContentCache_CreateDraftFromExisting_Call {
	return &MockContentCache_CreateDraftFromExisting_Call{Call: _e.mock.On("CreateDraftFromExisting", ctx, repoKey, pkgName, workspace)}
}

func (_c *MockContentCache_CreateDraftFromExisting_Call) Run(run func(ctx context.Context, repoKey repository.RepositoryKey, pkgName string, workspace string)) *MockContentCache_CreateDraftFromExisting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RepositoryKey
		if args[1] != nil {
			arg1 = args[1].(repository.RepositoryKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContentCache_CreateDraftFromExisting_Call) Return(packageRevisionDraftSlim repository.PackageRevisionDraftSlim, err error) *MockContentCache_CreateDraftFromExisting_Call {
	_c.Call.Return(packageRevisionDraftSlim, err)
	return _c
}

func (_c *MockContentCache_CreateDraftFromExisting_Call) RunAndReturn(run func(ctx context.Context, repoKey repository.RepositoryKey, pkgName string, workspace string) (repository.PackageRevisionDraftSlim, error)) *MockContentCache_CreateDraftFromExisting_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNewDraft provides a mock function for the type MockContentCache
func (_mock *MockContentCache) CreateNewDraft(ctx context.Context, repoKey repository.RepositoryKey, pkgName string, workspace string, lifecycle string) (repository.PackageRevisionDraftSlim, error) {
	ret := _mock.Called(ctx, repoKey, pkgName, workspace, lifecycle)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewDraft")
	}

	var r0 repository.PackageRevisionDraftSlim
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, string, string, string) (repository.PackageRevisionDraftSlim, error)); ok {
		return returnFunc(ctx, repoKey, pkgName, workspace, lifecycle)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, string, string, string) repository.PackageRevisionDraftSlim); ok {
		r0 = returnFunc(ctx, repoKey, pkgName, workspace, lifecycle)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PackageRevisionDraftSlim)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.RepositoryKey, string, string, string) error); ok {
		r1 = returnFunc(ctx, repoKey, pkgName, workspace, lifecycle)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentCache_CreateNewDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewDraft'
type MockContentCache_CreateNewDraft_Call struct {
	*mock.Call
}

// CreateNewDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - repoKey repository.RepositoryKey
//   - pkgName string
//   - workspace string
//   - lifecycle string
func (_e *MockContentCache_Expecter) CreateNewDraft(ctx interface{}, repoKey interface{}, pkgName interface{}, workspace interface{}, lifecycle interface{}) *MockContentCache_CreateNewDraft_Call {
	return &MockContentCache_CreateNewDraft_Call{Call: _e.mock.On("CreateNewDraft", ctx, repoKey, pkgName, workspace, lifecycle)}
}

func (_c *MockContentCache_CreateNewDraft_Call) Run(run func(ctx context.Context, repoKey repository.RepositoryKey, pkgName string, workspace string, lifecycle string)) *MockContentCache_CreateNewDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RepositoryKey
		if args[1] != nil {
			arg1 = args[1].(repository.RepositoryKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockContentCache_CreateNewDraft_Call) Return(packageRevisionDraftSlim repository.PackageRevisionDraftSlim, err error) *MockContentCache_CreateNewDraft_Call {
	_c.Call.Return(packageRevisionDraftSlim, err)
	return _c
}

func (_c *MockContentCache_CreateNewDraft_Call) RunAndReturn(run func(ctx context.Context, repoKey repository.RepositoryKey, pkgName string, workspace string, lifecycle string) (repository.PackageRevisionDraftSlim, error)) *MockContentCache_CreateNewDraft_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePackage provides a mock function for the type MockContentCache
func (_mock *MockContentCache) DeletePackage(ctx context.Context, repoKey repository.RepositoryKey, pkg string, workspace string) error {
	ret := _mock.Called(ctx, repoKey, pkg, workspace)

	if len(ret) == 0 {
		panic("no return value specified for DeletePackage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, string, string) error); ok {
		r0 = returnFunc(ctx, repoKey, pkg, workspace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContentCache_DeletePackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePackage'
type MockContentCache_DeletePackage_Call struct {
	*mock.Call
}

// DeletePackage is a helper method to define mock.On call
//   - ctx context.Context
//   - repoKey repository.RepositoryKey
//   - pkg string
//   - workspace string
func (_e *MockContentCache_Expecter) DeletePackage(ctx interface{}, repoKey interface{}, pkg interface{}, workspace interface{}) *MockContentCache_DeletePackage_Call {
	return &MockContentCache_DeletePackage_Call{Call: _e.mock.On("DeletePackage", ctx, repoKey, pkg, workspace)}
}

func (_c *MockContentCache_DeletePackage_Call) Run(run func(ctx context.Context, repoKey repository.RepositoryKey, pkg string, workspace string)) *MockContentCache_DeletePackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RepositoryKey
		if args[1] != nil {
			arg1 = args[1].(repository.RepositoryKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContentCache_DeletePackage_Call) Return(err error) *MockContentCache_DeletePackage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContentCache_DeletePackage_Call) RunAndReturn(run func(ctx context.Context, repoKey repository.RepositoryKey, pkg string, workspace string) error) *MockContentCache_DeletePackage_Call {
	_c.Call.Return(run)
	return _c
}

// GetPackageContent provides a mock function for the type MockContentCache
func (_mock *MockContentCache) GetPackageContent(ctx context.Context, repoKey repository.RepositoryKey, pkg string, workspace string) (repository.PackageContent, error) {
	ret := _mock.Called(ctx, repoKey, pkg, workspace)

	if len(ret) == 0 {
		panic("no return value specified for GetPackageContent")
	}

	var r0 repository.PackageContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, string, string) (repository.PackageContent, error)); ok {
		return returnFunc(ctx, repoKey, pkg, workspace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, string, string) repository.PackageContent); ok {
		r0 = returnFunc(ctx, repoKey, pkg, workspace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PackageContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.RepositoryKey, string, string) error); ok {
		r1 = returnFunc(ctx, repoKey, pkg, workspace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentCache_GetPackageContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPackageContent'
type MockContentCache_GetPackageContent_Call struct {
	*mock.Call
}

// GetPackageContent is a helper method to define mock.On call
//   - ctx context.Context
//   - repoKey repository.RepositoryKey
//   - pkg string
//   - workspace string
func (_e *MockContentCache_Expecter) GetPackageContent(ctx interface{}, repoKey interface{}, pkg interface{}, workspace interface{}) *MockContentCache_GetPackageContent_Call {
	return &MockContentCache_GetPackageContent_Call{Call: _e.mock.On("GetPackageContent", ctx, repoKey, pkg, workspace)}
}

func (_c *MockContentCache_GetPackageContent_Call) Run(run func(ctx context.Context, repoKey repository.RepositoryKey, pkg string, workspace string)) *MockContentCache_GetPackageContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RepositoryKey
		if args[1] != nil {
			arg1 = args[1].(repository.RepositoryKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContentCache_GetPackageContent_Call) Return(packageContent repository.PackageContent, err error) *MockContentCache_GetPackageContent_Call {
	_c.Call.Return(packageContent, err)
	return _c
}

func (_c *MockContentCache_GetPackageContent_Call) RunAndReturn(run func(ctx context.Context, repoKey repository.RepositoryKey, pkg string, workspace string) (repository.PackageContent, error)) *MockContentCache_GetPackageContent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLifecycle provides a mock function for the type MockContentCache
func (_mock *MockContentCache) UpdateLifecycle(ctx context.Context, repoKey repository.RepositoryKey, pkg string, workspace string, desired string) (repository.PackageContent, error) {
	ret := _mock.Called(ctx, repoKey, pkg, workspace, desired)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLifecycle")
	}

	var r0 repository.PackageContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, string, string, string) (repository.PackageContent, error)); ok {
		return returnFunc(ctx, repoKey, pkg, workspace, desired)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RepositoryKey, string, string, string) repository.PackageContent); ok {
		r0 = returnFunc(ctx, repoKey, pkg, workspace, desired)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PackageContent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.RepositoryKey, string, string, string) error); ok {
		r1 = returnFunc(ctx, repoKey, pkg, workspace, desired)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentCache_UpdateLifecycle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLifecycle'
type MockContentCache_UpdateLifecycle_Call struct {
	*mock.Call
}

// UpdateLifecycle is a helper method to define mock.On call
//   - ctx context.Context
//   - repoKey repository.RepositoryKey
//   - pkg string
//   - workspace string
//   - desired string
func (_e *MockContentCache_Expecter) UpdateLifecycle(ctx interface{}, repoKey interface{}, pkg interface{}, workspace interface{}, desired interface{}) *MockContentCache_UpdateLifecycle_Call {
	return &MockContentCache_UpdateLifecycle_Call{Call: _e.mock.On("UpdateLifecycle", ctx, repoKey, pkg, workspace, desired)}
}

func (_c *MockContentCache_UpdateLifecycle_Call) Run(run func(ctx context.Context, repoKey repository.RepositoryKey, pkg string, workspace string, desired string)) *MockContentCache_UpdateLifecycle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RepositoryKey
		if args[1] != nil {
			arg1 = args[1].(repository.RepositoryKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockContentCache_UpdateLifecycle_Call) Return(packageContent repository.PackageContent, err error) *MockContentCache_UpdateLifecycle_Call {
	_c.Call.Return(packageContent, err)
	return _c
}

func (_c *MockContentCache_UpdateLifecycle_Call) RunAndReturn(run func(ctx context.Context, repoKey repository.RepositoryKey, pkg string, workspace string, desired string) (repository.PackageContent, error)) *MockContentCache_UpdateLifecycle_Call {
	_c.Call.Return(run)
	return _c
}
