// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/kptdev/kpt/pkg/api/kptfile/v1"
	"github.com/nephio-project/porch/api/porch/v1alpha2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExternalPackageFetcher creates a new instance of MockExternalPackageFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExternalPackageFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExternalPackageFetcher {
	mock := &MockExternalPackageFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExternalPackageFetcher is an autogenerated mock type for the ExternalPackageFetcher type
type MockExternalPackageFetcher struct {
	mock.Mock
}

type MockExternalPackageFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExternalPackageFetcher) EXPECT() *MockExternalPackageFetcher_Expecter {
	return &MockExternalPackageFetcher_Expecter{mock: &_m.Mock}
}

// FetchExternalGitPackage provides a mock function for the type MockExternalPackageFetcher
func (_mock *MockExternalPackageFetcher) FetchExternalGitPackage(ctx context.Context, gitSpec *v1alpha2.GitPackage, namespace string) (map[string]string, v1.GitLock, error) {
	ret := _mock.Called(ctx, gitSpec, namespace)

	if len(ret) == 0 {
		panic("no return value specified for FetchExternalGitPackage")
	}

	var r0 map[string]string
	var r1 v1.GitLock
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha2.GitPackage, string) (map[string]string, v1.GitLock, error)); ok {
		return returnFunc(ctx, gitSpec, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha2.GitPackage, string) map[string]string); ok {
		r0 = returnFunc(ctx, gitSpec, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha2.GitPackage, string) v1.GitLock); ok {
		r1 = returnFunc(ctx, gitSpec, namespace)
	} else {
		r1 = ret.Get(1).(v1.GitLock)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *v1alpha2.GitPackage, string) error); ok {
		r2 = returnFunc(ctx, gitSpec, namespace)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockExternalPackageFetcher_FetchExternalGitPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchExternalGitPackage'
type MockExternalPackageFetcher_FetchExternalGitPackage_Call struct {
	*mock.Call
}

// FetchExternalGitPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - gitSpec *v1alpha2.GitPackage
//   - namespace string
func (_e *MockExternalPackageFetcher_Expecter) FetchExternalGitPackage(ctx interface{}, gitSpec interface{}, namespace interface{}) *MockExternalPackageFetcher_FetchExternalGitPackage_Call {
	return &MockExternalPackageFetcher_FetchExternalGitPackage_Call{Call: _e.mock.On("FetchExternalGitPackage", ctx, gitSpec, namespace)}
}

func (_c *MockExternalPackageFetcher_FetchExternalGitPackage_Call) Run(run func(ctx context.Context, gitSpec *v1alpha2.GitPackage, namespace string)) *MockExternalPackageFetcher_FetchExternalGitPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha2.GitPackage
		if args[1] != nil {
			arg1 = args[1].(*v1alpha2.GitPackage)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExternalPackageFetcher_FetchExternalGitPackage_Call) Return(stringToString map[string]string, gitLock v1.GitLock, err error) *MockExternalPackageFetcher_FetchExternalGitPackage_Call {
	_c.Call.Return(stringToString, gitLock, err)
	return _c
}

func (_c *MockExternalPackageFetcher_FetchExternalGitPackage_Call) RunAndReturn(run func(ctx context.Context, gitSpec *v1alpha2.GitPackage, namespace string) (map[string]string, v1.GitLock, error)) *MockExternalPackageFetcher_FetchExternalGitPackage_Call {
	_c.Call.Return(run)
	return _c
}
