// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"time"

	"github.com/kptdev/kpt/pkg/api/kptfile/v1"
	"github.com/nephio-project/porch/pkg/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPackageContent creates a new instance of MockPackageContent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageContent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageContent {
	mock := &MockPackageContent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPackageContent is an autogenerated mock type for the PackageContent type
type MockPackageContent struct {
	mock.Mock
}

type MockPackageContent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageContent) EXPECT() *MockPackageContent_Expecter {
	return &MockPackageContent_Expecter{mock: &_m.Mock}
}

// GetCommitInfo provides a mock function for the type MockPackageContent
func (_mock *MockPackageContent) GetCommitInfo() (time.Time, string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCommitInfo")
	}

	var r0 time.Time
	var r1 string
	if returnFunc, ok := ret.Get(0).(func() (time.Time, string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockPackageContent_GetCommitInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommitInfo'
type MockPackageContent_GetCommitInfo_Call struct {
	*mock.Call
}

// GetCommitInfo is a helper method to define mock.On call
func (_e *MockPackageContent_Expecter) GetCommitInfo() *MockPackageContent_GetCommitInfo_Call {
	return &MockPackageContent_GetCommitInfo_Call{Call: _e.mock.On("GetCommitInfo")}
}

func (_c *MockPackageContent_GetCommitInfo_Call) Run(run func()) *MockPackageContent_GetCommitInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageContent_GetCommitInfo_Call) Return(commitTime time.Time, commitAuthor string) *MockPackageContent_GetCommitInfo_Call {
	_c.Call.Return(commitTime, commitAuthor)
	return _c
}

func (_c *MockPackageContent_GetCommitInfo_Call) RunAndReturn(run func() (time.Time, string)) *MockPackageContent_GetCommitInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetKptfile provides a mock function for the type MockPackageContent
func (_mock *MockPackageContent) GetKptfile(ctx context.Context) (v1.KptFile, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKptfile")
	}

	var r0 v1.KptFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.KptFile, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.KptFile); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.KptFile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageContent_GetKptfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKptfile'
type MockPackageContent_GetKptfile_Call struct {
	*mock.Call
}

// GetKptfile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPackageContent_Expecter) GetKptfile(ctx interface{}) *MockPackageContent_GetKptfile_Call {
	return &MockPackageContent_GetKptfile_Call{Call: _e.mock.On("GetKptfile", ctx)}
}

func (_c *MockPackageContent_GetKptfile_Call) Run(run func(ctx context.Context)) *MockPackageContent_GetKptfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageContent_GetKptfile_Call) Return(kptFile v1.KptFile, err error) *MockPackageContent_GetKptfile_Call {
	_c.Call.Return(kptFile, err)
	return _c
}

func (_c *MockPackageContent_GetKptfile_Call) RunAndReturn(run func(ctx context.Context) (v1.KptFile, error)) *MockPackageContent_GetKptfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetLock provides a mock function for the type MockPackageContent
func (_mock *MockPackageContent) GetLock(ctx context.Context) (v1.Upstream, v1.UpstreamLock, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLock")
	}

	var r0 v1.Upstream
	var r1 v1.UpstreamLock
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.Upstream, v1.UpstreamLock, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.Upstream); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.Upstream)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) v1.UpstreamLock); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(v1.UpstreamLock)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPackageContent_GetLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLock'
type MockPackageContent_GetLock_Call struct {
	*mock.Call
}

// GetLock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPackageContent_Expecter) GetLock(ctx interface{}) *MockPackageContent_GetLock_Call {
	return &MockPackageContent_GetLock_Call{Call: _e.mock.On("GetLock", ctx)}
}

func (_c *MockPackageContent_GetLock_Call) Run(run func(ctx context.Context)) *MockPackageContent_GetLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageContent_GetLock_Call) Return(upstream v1.Upstream, v v1.UpstreamLock, err error) *MockPackageContent_GetLock_Call {
	_c.Call.Return(upstream, v, err)
	return _c
}

func (_c *MockPackageContent_GetLock_Call) RunAndReturn(run func(ctx context.Context) (v1.Upstream, v1.UpstreamLock, error)) *MockPackageContent_GetLock_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceContents provides a mock function for the type MockPackageContent
func (_mock *MockPackageContent) GetResourceContents(ctx context.Context) (map[string]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceContents")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageContent_GetResourceContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceContents'
type MockPackageContent_GetResourceContents_Call struct {
	*mock.Call
}

// GetResourceContents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPackageContent_Expecter) GetResourceContents(ctx interface{}) *MockPackageContent_GetResourceContents_Call {
	return &MockPackageContent_GetResourceContents_Call{Call: _e.mock.On("GetResourceContents", ctx)}
}

func (_c *MockPackageContent_GetResourceContents_Call) Run(run func(ctx context.Context)) *MockPackageContent_GetResourceContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageContent_GetResourceContents_Call) Return(stringToString map[string]string, err error) *MockPackageContent_GetResourceContents_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockPackageContent_GetResourceContents_Call) RunAndReturn(run func(ctx context.Context) (map[string]string, error)) *MockPackageContent_GetResourceContents_Call {
	_c.Call.Return(run)
	return _c
}

// GetUpstreamLock provides a mock function for the type MockPackageContent
func (_mock *MockPackageContent) GetUpstreamLock(ctx context.Context) (v1.Upstream, v1.UpstreamLock, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUpstreamLock")
	}

	var r0 v1.Upstream
	var r1 v1.UpstreamLock
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.Upstream, v1.UpstreamLock, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.Upstream); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.Upstream)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) v1.UpstreamLock); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(v1.UpstreamLock)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPackageContent_GetUpstreamLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpstreamLock'
type MockPackageContent_GetUpstreamLock_Call struct {
	*mock.Call
}

// GetUpstreamLock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPackageContent_Expecter) GetUpstreamLock(ctx interface{}) *MockPackageContent_GetUpstreamLock_Call {
	return &MockPackageContent_GetUpstreamLock_Call{Call: _e.mock.On("GetUpstreamLock", ctx)}
}

func (_c *MockPackageContent_GetUpstreamLock_Call) Run(run func(ctx context.Context)) *MockPackageContent_GetUpstreamLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageContent_GetUpstreamLock_Call) Return(upstream v1.Upstream, v v1.UpstreamLock, err error) *MockPackageContent_GetUpstreamLock_Call {
	_c.Call.Return(upstream, v, err)
	return _c
}

func (_c *MockPackageContent_GetUpstreamLock_Call) RunAndReturn(run func(ctx context.Context) (v1.Upstream, v1.UpstreamLock, error)) *MockPackageContent_GetUpstreamLock_Call {
	_c.Call.Return(run)
	return _c
}

// Key provides a mock function for the type MockPackageContent
func (_mock *MockPackageContent) Key() repository.PackageRevisionKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Key")
	}

	var r0 repository.PackageRevisionKey
	if returnFunc, ok := ret.Get(0).(func() repository.PackageRevisionKey); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(repository.PackageRevisionKey)
	}
	return r0
}

// MockPackageContent_Key_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Key'
type MockPackageContent_Key_Call struct {
	*mock.Call
}

// Key is a helper method to define mock.On call
func (_e *MockPackageContent_Expecter) Key() *MockPackageContent_Key_Call {
	return &MockPackageContent_Key_Call{Call: _e.mock.On("Key")}
}

func (_c *MockPackageContent_Key_Call) Run(run func()) *MockPackageContent_Key_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageContent_Key_Call) Return(packageRevisionKey repository.PackageRevisionKey) *MockPackageContent_Key_Call {
	_c.Call.Return(packageRevisionKey)
	return _c
}

func (_c *MockPackageContent_Key_Call) RunAndReturn(run func() repository.PackageRevisionKey) *MockPackageContent_Key_Call {
	_c.Call.Return(run)
	return _c
}

// Lifecycle provides a mock function for the type MockPackageContent
func (_mock *MockPackageContent) Lifecycle(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Lifecycle")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPackageContent_Lifecycle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lifecycle'
type MockPackageContent_Lifecycle_Call struct {
	*mock.Call
}

// Lifecycle is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPackageContent_Expecter) Lifecycle(ctx interface{}) *MockPackageContent_Lifecycle_Call {
	return &MockPackageContent_Lifecycle_Call{Call: _e.mock.On("Lifecycle", ctx)}
}

func (_c *MockPackageContent_Lifecycle_Call) Run(run func(ctx context.Context)) *MockPackageContent_Lifecycle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageContent_Lifecycle_Call) Return(s string) *MockPackageContent_Lifecycle_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPackageContent_Lifecycle_Call) RunAndReturn(run func(ctx context.Context) string) *MockPackageContent_Lifecycle_Call {
	_c.Call.Return(run)
	return _c
}
