# Copyright 2022-2025 The kpt and Nephio Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ServiceAccount
apiVersion: v1
metadata:
  name: porch-fn-runner
  namespace: porch-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: function-runner
  namespace: porch-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: function-runner
  template:
    metadata:
      labels:
        app: function-runner
    spec:
      serviceAccountName: porch-fn-runner
      containers:
        - name: function-runner
          image: docker.io/nephio/porch-function-runner:latest
          imagePullPolicy: IfNotPresent
          command:
            - /server
            - --config=/config.yaml
            - --functions=/functions
            - --pod-namespace=porch-system
            - --function-pod-template=kpt-function-eval-pod-template
            - --max-request-body-size=6291456 # Keep this in sync with porch-server's corresponding argument
          env:
            - name: WRAPPER_SERVER_IMAGE
              value: docker.io/nephio/porch-wrapper-server:latest
            - name: OTEL_METRICS_EXPORTER
              value: "prometheus"
            - name: OTEL_EXPORTER_PROMETHEUS_HOST
              value: localhost # Default value, showing for visibility
            - name: OTEL_EXPORTER_PROMETHEUS_PORT
              value: "9464" # Default value, showing for visibility
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-oltp:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SERVICE_NAME
              value: porch-function-runner
          ports:
            - containerPort: 9445
            - containerPort: 9464
              name: metrics
          # Add grpc readiness probe to ensure the cache is ready
          readinessProbe:
            exec:
              command:
                - /grpc-health-probe
                - -addr
                - localhost:9445
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
          volumeMounts:
            - mountPath: /pod-cache-config
              name: pod-cache-config-volume
      volumes:
        - name: pod-cache-config-volume
          configMap:
            name: pod-cache-config

---
apiVersion: v1
kind: Service
metadata:
  name: function-runner
  namespace: porch-system
spec:
  selector:
    app: function-runner
  ports:
    - port: 9445
      protocol: TCP
      targetPort: 9445

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-cache-config
  namespace: porch-system
data:
  pod-cache-config.yaml: |
    gcr.io/kpt-fn/apply-replacements:v0.1.1: 30m
    gcr.io/kpt-fn/apply-setters:v0.2.0: 30m
    gcr.io/kpt-fn/create-setters:v0.1.0: 30m
    gcr.io/kpt-fn/ensure-name-substring:v0.2.0: 30m
    gcr.io/kpt-fn/gatekeeper:v0.2.1: 30m
    gcr.io/kpt-fn/kubeval:v0.2.0: 30m
    gcr.io/kpt-fn/search-replace:v0.2.0: 30m
    gcr.io/kpt-fn/set-annotations:v0.1.4: 30m
    gcr.io/kpt-fn/set-enforcement-action:v0.1.0: 30m
    gcr.io/kpt-fn/set-image:v0.1.1: 30m
    gcr.io/kpt-fn/set-labels:v0.1.5: 30m
    gcr.io/kpt-fn/set-namespace:v0.4.1: 30m
    gcr.io/kpt-fn/starlark:v0.4.3: 30m
    gcr.io/kpt-fn/upsert-resource:v0.2.0: 30m
    gcr.io/kpt-fn/enable-gcp-services:v0.1.0: 30m
    gcr.io/kpt-fn/export-terraform:v0.1.0: 30m
    gcr.io/kpt-fn/generate-folders:v0.1.1: 30m
    gcr.io/kpt-fn/remove-local-config-resources:v0.1.0: 30m
    gcr.io/kpt-fn/set-project-id:v0.2.0: 30m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kpt-function-eval-pod-template
  namespace: porch-system
data:
  template: |
    apiVersion: v1
    kind: Pod
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: true
    spec:
      initContainers:
        - name: copy-wrapper-server
          image: porch-kind/porch-wrapper-server:test
          command: 
            - cp
            - -a
            - /wrapper-server/.
            - /wrapper-server-tools
          volumeMounts:
            - name: wrapper-server-tools
              mountPath: /wrapper-server-tools
      containers:
        - name: function
          image: image-replaced-by-kpt-func-image
          command: 
            - /wrapper-server-tools/wrapper-server
          env: 
            - name: OTEL_METRICS_EXPORTER
              value: "prometheus"
            - name: OTEL_EXPORTER_PROMETHEUS_HOST
              value: localhost # Default value, showing for visibility
            - name: OTEL_EXPORTER_PROMETHEUS_PORT
              value: "9464" # Default value, showing for visibility
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-oltp:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SERVICE_NAME
              value: porch-wrapper-server
          volumeMounts:
            - name: wrapper-server-tools
              mountPath: /wrapper-server-tools
      volumes:
        - name: wrapper-server-tools
          emptyDir: {}
  serviceTemplate: |
    apiVersion: v1
    kind: Service
    spec:
      ports:
      - port: 9446
        protocol: TCP
        targetPort: 9446
      selector:
        fn.kpt.dev/image: to-be-replaced
      type: ClusterIP
