FROM golang:1.22.1-alpine3.18 AS builder

WORKDIR /go/src

# Ensure the wrapper server and grpc-health-probe is statically linked so that they works in distroless-based images.
ENV CGO_ENABLED=0

COPY go.mod go.sum ./
COPY api/go.mod api/go.sum api/

RUN go install github.com/grpc-ecosystem/grpc-health-probe@v0.4.11
COPY func/ func/
RUN cd func ; go build -v -o /wrapper-server/wrapper-server ./wrapper-server
RUN cp $GOPATH/bin/grpc-health-probe /wrapper-server/

FROM alpine:3.18

COPY --from=builder /wrapper-server/* /wrapper-server/
