# Copyright 2022-2026 The kpt and Nephio Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG ALPINE_VERSION=latest

FROM golang:1.25.7-alpine AS builder

WORKDIR /go/src

# Ensure the wrapper server and grpc-health-probe is statically linked so that they works in distroless-based images.
ENV CGO_ENABLED=0

COPY go.mod go.sum ./

RUN go install github.com/grpc-ecosystem/grpc-health-probe@v0.4.11
COPY func/ func/
COPY ./api ./api
COPY ./pkg ./pkg
COPY ./internal ./internal
COPY ./third_party ./third_party

RUN cd func ; go build -v -o /wrapper-server/wrapper-server ./wrapper-server
RUN cp $GOPATH/bin/grpc-health-probe /wrapper-server/

FROM alpine:${ALPINE_VERSION}
RUN addgroup -g 10001 nonroot && \
    adduser -D -G nonroot -u 10001 nonroot

COPY --from=builder --chown=root:root --chmod=555 /wrapper-server/* /home/nonroot/wrapper-server/
USER nonroot:nonroot
