// Copyright 2022 The kpt and Nephio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code originally generated by "mdtogo", but
// no longer maintained that way.
package docs

var RpkgShort = `Manage packages.`
var RpkgLong = `
The ` + "`" + `rpkg` + "`" + ` command group contains subcommands for managing packages and revisions (versions) of these packages.
`

var ApproveShort = `Approve a proposal to publish a package revision.`
var ApproveLong = `
  porchctl rpkg approve [K8S_PACKAGE_REV_NAME...] [flags]

Args:

  K8S_PACKAGE_REV_NAME...:
    The kubernetes name of one or more package revisions. If more than
    one is provided, they must be space-separated.
`
var ApproveExamples = `
  # approve package revision 'example-repo.example-package-name.example-workspace'
  $ porchctl rpkg approve example-repo.example-package-name.example-workspace --namespace=example-namespace
`

var CloneShort = `Create a clone of an existing package revision.`
var CloneLong = `
  porchctl rpkg clone SOURCE_PACKAGE_REV TARGET_PACKAGE_NAME [flags]

Args:

  SOURCE_PACKAGE_REV:
    The source package that will be cloned to create the new package revision.
    The types of sources are supported:

      * OCI: A URI to a OCI repository must be provided.
        oci://oci-repository/package-name
      * Git: A URI to a git repository must be provided.
        https://git-repository.git/package-name
      * Package: The kubernetes name of a package revision already available in the
        repository.
        example-repo.example-package-name.example-workspace

  TARGET_PACKAGE_NAME:
    The name of the new package.


Flags:

  --directory
    Directory within the upstream repository where the upstream
    package revision is located. This only applies if the source package is in git
    or oci.

  --ref
    Ref in the upstream repository where the package revision
    is located. This can be a branch, a tag or a SHA. This only applies when the source package
    is in git.

  --repository
    This is the downstream repository which the package revision will be cloned to.

  --workspace
    The workspace name assigned to the new downstream package revision. The default value is v1.

  --strategy
    Update strategy that should be used when updating the new
    package revision. Must be one of:
    =resource-merge: (Default) Perform a structural comparison of the original
      updated resources, and merge the changes into the local package.
    =fast-forward: Fail without updating if the local package was modified since it was fetched.
    =force-delete-replace: Wipe all the local changes to the package and replace
      it with the remote version.
    =copy-merge: Copy all the remote changes to the local package.

  --secret-ref
    Name of the secret containing basic authentication used to authenticate with the upstream repository (git-only).
    Naturally, this secret has to exist in the kubernetes cluster and must be in the namespace
    where the package revision is to be created.
`
var CloneExamples = `
  # clone the 'example-repo.example-package-name.example-workspace' package and create a new package revision called
  # 'example-package-name-2' in the 'example-repo-2' repository with a new workspace named 'example-workspace-2' and 'force-delete-replace' update strategy.
  $ porchctl rpkg clone example-repo.example-package-name.example-workspace example-package-name-2 --repository=example-repo-2 --workspace=example-workspace-2 --strategy=force-delete-replace

  # clone the git repository at 'https://github.com/repo/blueprint.git' at reference 'base/v0' and in directory base. The new
  # package revision will be created in repository 'blueprint' and namespace 'default'.
  $ porchctl rpkg clone https://github.com/repo/blueprint.git example-downstream-package --repository=blueprint --ref=base/v0 --namespace=default --directory=base
`

var CopyShort = `Create a new package revision from an existing one.`
var CopyLong = `
  porchctl rpkg copy SOURCE_PACKAGE_REV_NAME [flags]

Args:

  SOURCE_K8S_PACKAGE_REV_NAME:
    The kubernetes name of the package revision that will be used as the source
    for creating a new package revision.

Flags:

  --workspace
    Workspace for the new package revision.
`
var CopyExamples = `
  # create a new package from package 'example-repo.example-package-name.example-workspace' in the new workspace 'example-workspace-2'
  $ porchctl rpkg copy example-repo.example-package-name.example-workspace --workspace=example-workspace-2 --namespace=example-namespace
`

var DelShort = `Delete a package revision.`
var DelLong = `
  porchctl rpkg del K8S_PACKAGE_REV_NAME... [flags]

Args:

  K8S_PACKAGE_REV_NAME...:
    The kubernetes name of one or more package revisions. If more than
    one is provided, they must be space-separated.
`
var DelExamples = `
  # remove package revision 'example-repo.example-package-name.example-workspace'
  $ porchctl rpkg del example-repo.example-package-name.example-workspace -n example-namespace
`

var GetShort = `List package revisions in registered repositories.`
var GetLong = `
  porchctl rpkg get [K8S_PACKAGE_REV_NAME] [flags]

Args:

  K8S_PACKAGE_REV_NAME:
    The kubernetes name of a package revision. If provided, only that specific
    package revision will be shown. Defaults to showing all package
    revisions from all repositories.

Flags:

  --name
    Name of the packages to get. Any package whose name contains
    this value will be included in the results.

  --revision
    Revision of the package to get. Any package whose revision
    matches this value will be included in the results.
`
var GetExamples = `
  # get a specific package revision using its kubernetes resource name in the 'example-namespace' namespace
  $ porchctl rpkg get example-repo.example-package-name.example-workspace --namespace=example-namespace

  # get a specific package revision named 'example-package-name' in the 'example-namespace' namespace
  $ porchctl rpkg get --name=example-package-name --namespace=example-namespace

  # get all package revisions in the 'example-namespace' namespace
  $ porchctl rpkg get --namespace=example-namespace

  # get all package revisions with revision '0'
  $ porchctl rpkg get --revision=0
`

var InitShort = `Initializes a new package revision in a repository.`
var InitLong = `
  porchctl rpkg init PACKAGE_NAME [flags]

Args:

  PACKAGE_NAME:
    The name of the new package.

Flags:

  --repository
    Repository in which the new package will be created.

  --workspace
    Workspace of the new package.

  --description
    Short description of the package

  --keywords
    List of keywords for the package

  --site
    Link to page with information about the package
`
var InitExamples = `
  # create a new package named 'example-package-name' in the repository 'example-repository' which exists in the namespace 'example-namespace'.
  $ porchctl rpkg init example-package-name --repository=example-repository --workspace=example-workspace --namespace=example-namespace
`

var ProposeShort = `Propose that a package revision should be published.`
var ProposeLong = `
  porchctl rpkg propose [K8S_PACKAGE_REV_NAME...] [flags]

Args:

  K8S_PACKAGE_REV_NAME...:
    The kubernetes name of one or more package revisions. If more than
    one is provided, they must be space-separated.
`
var ProposeExamples = `
  # propose that package revision 'example-repo.example-package-name.example-workspace' should be finalized.
  $ porchctl rpkg propose example-repo.example-package-name.example-workspace --namespace=example-namespace
`

var ProposeDeleteShort = `Propose deletion of a published package revision.`
var ProposeDeleteLong = `
  porchctl rpkg propose-delete K8S_PACKAGE_REV_NAME... [flags]

Args:

  K8S_PACKAGE_REV_NAME...:
  The kubernetes name of one or more package revisions. If more than
  one is provided, they must be space-separated.
`
var ProposeDeleteExamples = `
  # Propose published package revision 'example-repo.example-package-name.example-workspace' for deletion.
  $ porchctl rpkg propose-delete example-repo.example-package-name.example-workspace --namespace=example-namespace
`

var PullShort = `Pull the content of the package revision.`
var PullLong = `
  porchctl rpkg pull K8S_PACKAGE_REV_NAME [DIR] [flags]

Args:

  K8S_PACKAGE_REV_NAME:
    The kubernetes name of a an existing package revision in a repository.

  DIR:
    A local directory where the package manifests will be written.
    If not provided, the manifests are written to stdout.
`
var PullExamples = `
  # pull the content of package revision 'example-repo.example-package-name.example-workspace'
  $ porchctl rpkg pull example-repo.example-package-name.example-workspace --namespace=example-namespace
`

var PushShort = `Push resources to a package revision.`
var PushLong = `
  porchctl rpkg push K8S_PACKAGE_REV_NAME [DIR] [flags]

Args:

  K8S_PACKAGE_REV_NAME:
    The kubernetes name of a an existing package revision in a repository.

  DIR:
    A local directory with the new manifest. If the manifests have be read from stdin, use '-' in place of DIR.
`
var PushExamples = `
  # update the package revision 'example-repo.example-package-name.example-workspace' with the resources
  # in the './example-package-dir' directory
  $ porchctl rpkg push example-repo.example-package-name.example-workspace ./example-package-dir --namespace=example-namespace

  # update the package revision 'example-repo.example-package-name.example-workspace' with the resources
  # using 'stdin'
  $ porchctl rpkg push example-repo.example-package-name.example-workspace - <stdin> --namespace=example-namespace
`

var RejectShort = `Reject a proposal to publish or delete a package revision.`
var RejectLong = `
  porchctl rpkg reject [K8S_PACKAGE_REV_NAME...] [flags]

Args:

  K8S_PACKAGE_REV_NAME...:
    The kubernetes name of one or more package revisions. If more than
    one is provided, they must be space-separated.
`
var RejectExamples = `
  # reject the proposal for package revision 'example-repo.example-package-name.example-workspace'
  $ porchctl rpkg reject example-repo.example-package-name.example-workspace --namespace=example-namespace
`

var UpgradeShort = `Create a new revision which upgrades a published downstream to a more recent published revision of its upstream package.`
var UpgradeLong = `
  porchctl rpkg upgrade SOURCE_PACKAGE_REVISION [flags]

Args:

  SOURCE_PACKAGE_REVISION:
  The target downstream package revision to be upgraded. Must be published
  and must be coming from a package that has an upstream package (typically
  this means that it was cloned from another package).


Flags:

  --revision
  (Optional) The revision number of the upstream kpt package that the target
  downstream package revision (SOURCE_PACKAGE_REVISION) should be upgraded to.
  The corresponding revision must be published.

  --workspace
  The workspace name of the newly created package revision.

  --strategy
  (Optional) The strategy to use for the upgrade.
  Options: resource-merge (default), fast-forward, force-delete-replace, copy-merge.

  --discover
  If set, search for available updates instead of performing an update.
  Setting this to 'upstream' will discover upstream updates of downstream packages.
  Setting this to 'downstream' will discover downstream package revisions of upstream packages that need to be updated.
`
var UpgradeExamples = `
  # discover available upstream updates for downstream packages
  $ porchctl rpkg upgrade --discover=upstream

  # upgrade deployment.some-package.v1 package to v3 of its upstream
  $ porchctl rpkg upgrade deployment.some-package.v1 --revision=3 --workspace=v2

  # upgrade deployment.some-package.v1 package to the latest of its upstream
  $ porchctl rpkg upgrade deployment.some-package.v1 --workspace=v2

  # upgrade deployment.some-package.v1 package to v3 of its upstream, using copy-merge strategy
  $ porchctl rpkg upgrade deployment.some-package.v1 --revision=3 --workspace=v2 --strategy=copy-merge
`
