// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cachetypes

import (
	"context"

	"github.com/nephio-project/porch/api/porchconfig/v1alpha1"
	"github.com/nephio-project/porch/pkg/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// CloseRepository provides a mock function for the type MockCache
func (_mock *MockCache) CloseRepository(ctx context.Context, repositorySpec *v1alpha1.Repository, allRepos []v1alpha1.Repository) error {
	ret := _mock.Called(ctx, repositorySpec, allRepos)

	if len(ret) == 0 {
		panic("no return value specified for CloseRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.Repository, []v1alpha1.Repository) error); ok {
		r0 = returnFunc(ctx, repositorySpec, allRepos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_CloseRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseRepository'
type MockCache_CloseRepository_Call struct {
	*mock.Call
}

// CloseRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - repositorySpec *v1alpha1.Repository
//   - allRepos []v1alpha1.Repository
func (_e *MockCache_Expecter) CloseRepository(ctx interface{}, repositorySpec interface{}, allRepos interface{}) *MockCache_CloseRepository_Call {
	return &MockCache_CloseRepository_Call{Call: _e.mock.On("CloseRepository", ctx, repositorySpec, allRepos)}
}

func (_c *MockCache_CloseRepository_Call) Run(run func(ctx context.Context, repositorySpec *v1alpha1.Repository, allRepos []v1alpha1.Repository)) *MockCache_CloseRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.Repository
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.Repository)
		}
		var arg2 []v1alpha1.Repository
		if args[2] != nil {
			arg2 = args[2].([]v1alpha1.Repository)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_CloseRepository_Call) Return(err error) *MockCache_CloseRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_CloseRepository_Call) RunAndReturn(run func(ctx context.Context, repositorySpec *v1alpha1.Repository, allRepos []v1alpha1.Repository) error) *MockCache_CloseRepository_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepositories provides a mock function for the type MockCache
func (_mock *MockCache) GetRepositories() []*v1alpha1.Repository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepositories")
	}

	var r0 []*v1alpha1.Repository
	if returnFunc, ok := ret.Get(0).(func() []*v1alpha1.Repository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1alpha1.Repository)
		}
	}
	return r0
}

// MockCache_GetRepositories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepositories'
type MockCache_GetRepositories_Call struct {
	*mock.Call
}

// GetRepositories is a helper method to define mock.On call
func (_e *MockCache_Expecter) GetRepositories() *MockCache_GetRepositories_Call {
	return &MockCache_GetRepositories_Call{Call: _e.mock.On("GetRepositories")}
}

func (_c *MockCache_GetRepositories_Call) Run(run func()) *MockCache_GetRepositories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_GetRepositories_Call) Return(repositorys []*v1alpha1.Repository) *MockCache_GetRepositories_Call {
	_c.Call.Return(repositorys)
	return _c
}

func (_c *MockCache_GetRepositories_Call) RunAndReturn(run func() []*v1alpha1.Repository) *MockCache_GetRepositories_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepository provides a mock function for the type MockCache
func (_mock *MockCache) GetRepository(repositoryKey repository.RepositoryKey) repository.Repository {
	ret := _mock.Called(repositoryKey)

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 repository.Repository
	if returnFunc, ok := ret.Get(0).(func(repository.RepositoryKey) repository.Repository); ok {
		r0 = returnFunc(repositoryKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Repository)
		}
	}
	return r0
}

// MockCache_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type MockCache_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
//   - repositoryKey repository.RepositoryKey
func (_e *MockCache_Expecter) GetRepository(repositoryKey interface{}) *MockCache_GetRepository_Call {
	return &MockCache_GetRepository_Call{Call: _e.mock.On("GetRepository", repositoryKey)}
}

func (_c *MockCache_GetRepository_Call) Run(run func(repositoryKey repository.RepositoryKey)) *MockCache_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 repository.RepositoryKey
		if args[0] != nil {
			arg0 = args[0].(repository.RepositoryKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_GetRepository_Call) Return(repository1 repository.Repository) *MockCache_GetRepository_Call {
	_c.Call.Return(repository1)
	return _c
}

func (_c *MockCache_GetRepository_Call) RunAndReturn(run func(repositoryKey repository.RepositoryKey) repository.Repository) *MockCache_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// OpenRepository provides a mock function for the type MockCache
func (_mock *MockCache) OpenRepository(ctx context.Context, repositorySpec *v1alpha1.Repository) (repository.Repository, error) {
	ret := _mock.Called(ctx, repositorySpec)

	if len(ret) == 0 {
		panic("no return value specified for OpenRepository")
	}

	var r0 repository.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.Repository) (repository.Repository, error)); ok {
		return returnFunc(ctx, repositorySpec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.Repository) repository.Repository); ok {
		r0 = returnFunc(ctx, repositorySpec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha1.Repository) error); ok {
		r1 = returnFunc(ctx, repositorySpec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_OpenRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenRepository'
type MockCache_OpenRepository_Call struct {
	*mock.Call
}

// OpenRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - repositorySpec *v1alpha1.Repository
func (_e *MockCache_Expecter) OpenRepository(ctx interface{}, repositorySpec interface{}) *MockCache_OpenRepository_Call {
	return &MockCache_OpenRepository_Call{Call: _e.mock.On("OpenRepository", ctx, repositorySpec)}
}

func (_c *MockCache_OpenRepository_Call) Run(run func(ctx context.Context, repositorySpec *v1alpha1.Repository)) *MockCache_OpenRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.Repository
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.Repository)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_OpenRepository_Call) Return(repository1 repository.Repository, err error) *MockCache_OpenRepository_Call {
	_c.Call.Return(repository1, err)
	return _c
}

func (_c *MockCache_OpenRepository_Call) RunAndReturn(run func(ctx context.Context, repositorySpec *v1alpha1.Repository) (repository.Repository, error)) *MockCache_OpenRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRepository provides a mock function for the type MockCache
func (_mock *MockCache) UpdateRepository(ctx context.Context, repositorySpec *v1alpha1.Repository) error {
	ret := _mock.Called(ctx, repositorySpec)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.Repository) error); ok {
		r0 = returnFunc(ctx, repositorySpec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_UpdateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRepository'
type MockCache_UpdateRepository_Call struct {
	*mock.Call
}

// UpdateRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - repositorySpec *v1alpha1.Repository
func (_e *MockCache_Expecter) UpdateRepository(ctx interface{}, repositorySpec interface{}) *MockCache_UpdateRepository_Call {
	return &MockCache_UpdateRepository_Call{Call: _e.mock.On("UpdateRepository", ctx, repositorySpec)}
}

func (_c *MockCache_UpdateRepository_Call) Run(run func(ctx context.Context, repositorySpec *v1alpha1.Repository)) *MockCache_UpdateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.Repository
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.Repository)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_UpdateRepository_Call) Return(err error) *MockCache_UpdateRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_UpdateRepository_Call) RunAndReturn(run func(ctx context.Context, repositorySpec *v1alpha1.Repository) error) *MockCache_UpdateRepository_Call {
	_c.Call.Return(run)
	return _c
}
