//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 The kpt and Nephio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	porch "github.com/nephio-project/porch/api/porch"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Condition)(nil), (*porch.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Condition_To_porch_Condition(a.(*Condition), b.(*porch.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_Condition_To_v1alpha1_Condition(a.(*porch.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Field)(nil), (*porch.Field)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Field_To_porch_Field(a.(*Field), b.(*porch.Field), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.Field)(nil), (*Field)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_Field_To_v1alpha1_Field(a.(*porch.Field), b.(*Field), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*File)(nil), (*porch.File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_File_To_porch_File(a.(*File), b.(*porch.File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.File)(nil), (*File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_File_To_v1alpha1_File(a.(*porch.File), b.(*File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Function)(nil), (*porch.Function)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Function_To_porch_Function(a.(*Function), b.(*porch.Function), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.Function)(nil), (*Function)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_Function_To_v1alpha1_Function(a.(*porch.Function), b.(*Function), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FunctionConfig)(nil), (*porch.FunctionConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FunctionConfig_To_porch_FunctionConfig(a.(*FunctionConfig), b.(*porch.FunctionConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.FunctionConfig)(nil), (*FunctionConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_FunctionConfig_To_v1alpha1_FunctionConfig(a.(*porch.FunctionConfig), b.(*FunctionConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FunctionEvalTaskSpec)(nil), (*porch.FunctionEvalTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FunctionEvalTaskSpec_To_porch_FunctionEvalTaskSpec(a.(*FunctionEvalTaskSpec), b.(*porch.FunctionEvalTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.FunctionEvalTaskSpec)(nil), (*FunctionEvalTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_FunctionEvalTaskSpec_To_v1alpha1_FunctionEvalTaskSpec(a.(*porch.FunctionEvalTaskSpec), b.(*FunctionEvalTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FunctionList)(nil), (*porch.FunctionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FunctionList_To_porch_FunctionList(a.(*FunctionList), b.(*porch.FunctionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.FunctionList)(nil), (*FunctionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_FunctionList_To_v1alpha1_FunctionList(a.(*porch.FunctionList), b.(*FunctionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FunctionRef)(nil), (*porch.FunctionRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FunctionRef_To_porch_FunctionRef(a.(*FunctionRef), b.(*porch.FunctionRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.FunctionRef)(nil), (*FunctionRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_FunctionRef_To_v1alpha1_FunctionRef(a.(*porch.FunctionRef), b.(*FunctionRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FunctionSpec)(nil), (*porch.FunctionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FunctionSpec_To_porch_FunctionSpec(a.(*FunctionSpec), b.(*porch.FunctionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.FunctionSpec)(nil), (*FunctionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_FunctionSpec_To_v1alpha1_FunctionSpec(a.(*porch.FunctionSpec), b.(*FunctionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FunctionStatus)(nil), (*porch.FunctionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FunctionStatus_To_porch_FunctionStatus(a.(*FunctionStatus), b.(*porch.FunctionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.FunctionStatus)(nil), (*FunctionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_FunctionStatus_To_v1alpha1_FunctionStatus(a.(*porch.FunctionStatus), b.(*FunctionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitLock)(nil), (*porch.GitLock)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GitLock_To_porch_GitLock(a.(*GitLock), b.(*porch.GitLock), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.GitLock)(nil), (*GitLock)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_GitLock_To_v1alpha1_GitLock(a.(*porch.GitLock), b.(*GitLock), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GitPorchPkg)(nil), (*porch.GitPorchPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GitPorchPkg_To_porch_GitPorchPkg(a.(*GitPorchPkg), b.(*porch.GitPorchPkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.GitPorchPkg)(nil), (*GitPorchPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_GitPorchPkg_To_v1alpha1_GitPorchPkg(a.(*porch.GitPorchPkg), b.(*GitPorchPkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NameMeta)(nil), (*porch.NameMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NameMeta_To_porch_NameMeta(a.(*NameMeta), b.(*porch.NameMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.NameMeta)(nil), (*NameMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_NameMeta_To_v1alpha1_NameMeta(a.(*porch.NameMeta), b.(*NameMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OciPorchPkg)(nil), (*porch.OciPorchPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OciPorchPkg_To_porch_OciPorchPkg(a.(*OciPorchPkg), b.(*porch.OciPorchPkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.OciPorchPkg)(nil), (*OciPorchPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_OciPorchPkg_To_v1alpha1_OciPorchPkg(a.(*porch.OciPorchPkg), b.(*OciPorchPkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ParentReference)(nil), (*porch.ParentReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ParentReference_To_porch_ParentReference(a.(*ParentReference), b.(*porch.ParentReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.ParentReference)(nil), (*ParentReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_ParentReference_To_v1alpha1_ParentReference(a.(*porch.ParentReference), b.(*ParentReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PatchSpec)(nil), (*porch.PatchSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PatchSpec_To_porch_PatchSpec(a.(*PatchSpec), b.(*porch.PatchSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PatchSpec)(nil), (*PatchSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PatchSpec_To_v1alpha1_PatchSpec(a.(*porch.PatchSpec), b.(*PatchSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkg)(nil), (*porch.PorchPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkg_To_porch_PorchPkg(a.(*PorchPkg), b.(*porch.PorchPkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkg)(nil), (*PorchPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkg_To_v1alpha1_PorchPkg(a.(*porch.PorchPkg), b.(*PorchPkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgCloneTaskSpec)(nil), (*porch.PorchPkgCloneTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgCloneTaskSpec_To_porch_PorchPkgCloneTaskSpec(a.(*PorchPkgCloneTaskSpec), b.(*porch.PorchPkgCloneTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgCloneTaskSpec)(nil), (*PorchPkgCloneTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgCloneTaskSpec_To_v1alpha1_PorchPkgCloneTaskSpec(a.(*porch.PorchPkgCloneTaskSpec), b.(*PorchPkgCloneTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgEditTaskSpec)(nil), (*porch.PorchPkgEditTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgEditTaskSpec_To_porch_PorchPkgEditTaskSpec(a.(*PorchPkgEditTaskSpec), b.(*porch.PorchPkgEditTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgEditTaskSpec)(nil), (*PorchPkgEditTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgEditTaskSpec_To_v1alpha1_PorchPkgEditTaskSpec(a.(*porch.PorchPkgEditTaskSpec), b.(*PorchPkgEditTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgInitTaskSpec)(nil), (*porch.PorchPkgInitTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgInitTaskSpec_To_porch_PorchPkgInitTaskSpec(a.(*PorchPkgInitTaskSpec), b.(*porch.PorchPkgInitTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgInitTaskSpec)(nil), (*PorchPkgInitTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgInitTaskSpec_To_v1alpha1_PorchPkgInitTaskSpec(a.(*porch.PorchPkgInitTaskSpec), b.(*PorchPkgInitTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgList)(nil), (*porch.PorchPkgList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgList_To_porch_PorchPkgList(a.(*PorchPkgList), b.(*porch.PorchPkgList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgList)(nil), (*PorchPkgList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgList_To_v1alpha1_PorchPkgList(a.(*porch.PorchPkgList), b.(*PorchPkgList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgPatchTaskSpec)(nil), (*porch.PorchPkgPatchTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgPatchTaskSpec_To_porch_PorchPkgPatchTaskSpec(a.(*PorchPkgPatchTaskSpec), b.(*porch.PorchPkgPatchTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgPatchTaskSpec)(nil), (*PorchPkgPatchTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgPatchTaskSpec_To_v1alpha1_PorchPkgPatchTaskSpec(a.(*porch.PorchPkgPatchTaskSpec), b.(*PorchPkgPatchTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgRevision)(nil), (*porch.PorchPkgRevision)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgRevision_To_porch_PorchPkgRevision(a.(*PorchPkgRevision), b.(*porch.PorchPkgRevision), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgRevision)(nil), (*PorchPkgRevision)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgRevision_To_v1alpha1_PorchPkgRevision(a.(*porch.PorchPkgRevision), b.(*PorchPkgRevision), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgRevisionList)(nil), (*porch.PorchPkgRevisionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgRevisionList_To_porch_PorchPkgRevisionList(a.(*PorchPkgRevisionList), b.(*porch.PorchPkgRevisionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgRevisionList)(nil), (*PorchPkgRevisionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgRevisionList_To_v1alpha1_PorchPkgRevisionList(a.(*porch.PorchPkgRevisionList), b.(*PorchPkgRevisionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgRevisionRef)(nil), (*porch.PorchPkgRevisionRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgRevisionRef_To_porch_PorchPkgRevisionRef(a.(*PorchPkgRevisionRef), b.(*porch.PorchPkgRevisionRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgRevisionRef)(nil), (*PorchPkgRevisionRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgRevisionRef_To_v1alpha1_PorchPkgRevisionRef(a.(*porch.PorchPkgRevisionRef), b.(*PorchPkgRevisionRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgRevisionResources)(nil), (*porch.PorchPkgRevisionResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgRevisionResources_To_porch_PorchPkgRevisionResources(a.(*PorchPkgRevisionResources), b.(*porch.PorchPkgRevisionResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgRevisionResources)(nil), (*PorchPkgRevisionResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgRevisionResources_To_v1alpha1_PorchPkgRevisionResources(a.(*porch.PorchPkgRevisionResources), b.(*PorchPkgRevisionResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgRevisionResourcesList)(nil), (*porch.PorchPkgRevisionResourcesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgRevisionResourcesList_To_porch_PorchPkgRevisionResourcesList(a.(*PorchPkgRevisionResourcesList), b.(*porch.PorchPkgRevisionResourcesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgRevisionResourcesList)(nil), (*PorchPkgRevisionResourcesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgRevisionResourcesList_To_v1alpha1_PorchPkgRevisionResourcesList(a.(*porch.PorchPkgRevisionResourcesList), b.(*PorchPkgRevisionResourcesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgRevisionResourcesSpec)(nil), (*porch.PorchPkgRevisionResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgRevisionResourcesSpec_To_porch_PorchPkgRevisionResourcesSpec(a.(*PorchPkgRevisionResourcesSpec), b.(*porch.PorchPkgRevisionResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgRevisionResourcesSpec)(nil), (*PorchPkgRevisionResourcesSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgRevisionResourcesSpec_To_v1alpha1_PorchPkgRevisionResourcesSpec(a.(*porch.PorchPkgRevisionResourcesSpec), b.(*PorchPkgRevisionResourcesSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgRevisionResourcesStatus)(nil), (*porch.PorchPkgRevisionResourcesStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgRevisionResourcesStatus_To_porch_PorchPkgRevisionResourcesStatus(a.(*PorchPkgRevisionResourcesStatus), b.(*porch.PorchPkgRevisionResourcesStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgRevisionResourcesStatus)(nil), (*PorchPkgRevisionResourcesStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgRevisionResourcesStatus_To_v1alpha1_PorchPkgRevisionResourcesStatus(a.(*porch.PorchPkgRevisionResourcesStatus), b.(*PorchPkgRevisionResourcesStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgRevisionSpec)(nil), (*porch.PorchPkgRevisionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgRevisionSpec_To_porch_PorchPkgRevisionSpec(a.(*PorchPkgRevisionSpec), b.(*porch.PorchPkgRevisionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgRevisionSpec)(nil), (*PorchPkgRevisionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgRevisionSpec_To_v1alpha1_PorchPkgRevisionSpec(a.(*porch.PorchPkgRevisionSpec), b.(*PorchPkgRevisionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgRevisionStatus)(nil), (*porch.PorchPkgRevisionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgRevisionStatus_To_porch_PorchPkgRevisionStatus(a.(*PorchPkgRevisionStatus), b.(*porch.PorchPkgRevisionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgRevisionStatus)(nil), (*PorchPkgRevisionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgRevisionStatus_To_v1alpha1_PorchPkgRevisionStatus(a.(*porch.PorchPkgRevisionStatus), b.(*PorchPkgRevisionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgSpec)(nil), (*porch.PorchPkgSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgSpec_To_porch_PorchPkgSpec(a.(*PorchPkgSpec), b.(*porch.PorchPkgSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgSpec)(nil), (*PorchPkgSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgSpec_To_v1alpha1_PorchPkgSpec(a.(*porch.PorchPkgSpec), b.(*PorchPkgSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgStatus)(nil), (*porch.PorchPkgStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgStatus_To_porch_PorchPkgStatus(a.(*PorchPkgStatus), b.(*porch.PorchPkgStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgStatus)(nil), (*PorchPkgStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgStatus_To_v1alpha1_PorchPkgStatus(a.(*porch.PorchPkgStatus), b.(*PorchPkgStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PorchPkgUpdateTaskSpec)(nil), (*porch.PorchPkgUpdateTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PorchPkgUpdateTaskSpec_To_porch_PorchPkgUpdateTaskSpec(a.(*PorchPkgUpdateTaskSpec), b.(*porch.PorchPkgUpdateTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.PorchPkgUpdateTaskSpec)(nil), (*PorchPkgUpdateTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_PorchPkgUpdateTaskSpec_To_v1alpha1_PorchPkgUpdateTaskSpec(a.(*porch.PorchPkgUpdateTaskSpec), b.(*PorchPkgUpdateTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReadinessGate)(nil), (*porch.ReadinessGate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ReadinessGate_To_porch_ReadinessGate(a.(*ReadinessGate), b.(*porch.ReadinessGate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.ReadinessGate)(nil), (*ReadinessGate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_ReadinessGate_To_v1alpha1_ReadinessGate(a.(*porch.ReadinessGate), b.(*ReadinessGate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RenderStatus)(nil), (*porch.RenderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RenderStatus_To_porch_RenderStatus(a.(*RenderStatus), b.(*porch.RenderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.RenderStatus)(nil), (*RenderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_RenderStatus_To_v1alpha1_RenderStatus(a.(*porch.RenderStatus), b.(*RenderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepositoryRef)(nil), (*porch.RepositoryRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepositoryRef_To_porch_RepositoryRef(a.(*RepositoryRef), b.(*porch.RepositoryRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.RepositoryRef)(nil), (*RepositoryRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_RepositoryRef_To_v1alpha1_RepositoryRef(a.(*porch.RepositoryRef), b.(*RepositoryRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceIdentifier)(nil), (*porch.ResourceIdentifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceIdentifier_To_porch_ResourceIdentifier(a.(*ResourceIdentifier), b.(*porch.ResourceIdentifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.ResourceIdentifier)(nil), (*ResourceIdentifier)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_ResourceIdentifier_To_v1alpha1_ResourceIdentifier(a.(*porch.ResourceIdentifier), b.(*ResourceIdentifier), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Result)(nil), (*porch.Result)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Result_To_porch_Result(a.(*Result), b.(*porch.Result), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.Result)(nil), (*Result)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_Result_To_v1alpha1_Result(a.(*porch.Result), b.(*Result), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResultItem)(nil), (*porch.ResultItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResultItem_To_porch_ResultItem(a.(*ResultItem), b.(*porch.ResultItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.ResultItem)(nil), (*ResultItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_ResultItem_To_v1alpha1_ResultItem(a.(*porch.ResultItem), b.(*ResultItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResultList)(nil), (*porch.ResultList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResultList_To_porch_ResultList(a.(*ResultList), b.(*porch.ResultList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.ResultList)(nil), (*ResultList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_ResultList_To_v1alpha1_ResultList(a.(*porch.ResultList), b.(*ResultList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretRef)(nil), (*porch.SecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretRef_To_porch_SecretRef(a.(*SecretRef), b.(*porch.SecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.SecretRef)(nil), (*SecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_SecretRef_To_v1alpha1_SecretRef(a.(*porch.SecretRef), b.(*SecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Selector)(nil), (*porch.Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Selector_To_porch_Selector(a.(*Selector), b.(*porch.Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.Selector)(nil), (*Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_Selector_To_v1alpha1_Selector(a.(*porch.Selector), b.(*Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Task)(nil), (*porch.Task)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Task_To_porch_Task(a.(*Task), b.(*porch.Task), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.Task)(nil), (*Task)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_Task_To_v1alpha1_Task(a.(*porch.Task), b.(*Task), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TaskResult)(nil), (*porch.TaskResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TaskResult_To_porch_TaskResult(a.(*TaskResult), b.(*porch.TaskResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.TaskResult)(nil), (*TaskResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_TaskResult_To_v1alpha1_TaskResult(a.(*porch.TaskResult), b.(*TaskResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UpstreamLock)(nil), (*porch.UpstreamLock)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpstreamLock_To_porch_UpstreamLock(a.(*UpstreamLock), b.(*porch.UpstreamLock), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.UpstreamLock)(nil), (*UpstreamLock)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_UpstreamLock_To_v1alpha1_UpstreamLock(a.(*porch.UpstreamLock), b.(*UpstreamLock), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UpstreamPorchPkg)(nil), (*porch.UpstreamPorchPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpstreamPorchPkg_To_porch_UpstreamPorchPkg(a.(*UpstreamPorchPkg), b.(*porch.UpstreamPorchPkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*porch.UpstreamPorchPkg)(nil), (*UpstreamPorchPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_porch_UpstreamPorchPkg_To_v1alpha1_UpstreamPorchPkg(a.(*porch.UpstreamPorchPkg), b.(*UpstreamPorchPkg), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Condition_To_porch_Condition(in *Condition, out *porch.Condition, s conversion.Scope) error {
	out.Type = in.Type
	out.Status = porch.ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_Condition_To_porch_Condition is an autogenerated conversion function.
func Convert_v1alpha1_Condition_To_porch_Condition(in *Condition, out *porch.Condition, s conversion.Scope) error {
	return autoConvert_v1alpha1_Condition_To_porch_Condition(in, out, s)
}

func autoConvert_porch_Condition_To_v1alpha1_Condition(in *porch.Condition, out *Condition, s conversion.Scope) error {
	out.Type = in.Type
	out.Status = ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_porch_Condition_To_v1alpha1_Condition is an autogenerated conversion function.
func Convert_porch_Condition_To_v1alpha1_Condition(in *porch.Condition, out *Condition, s conversion.Scope) error {
	return autoConvert_porch_Condition_To_v1alpha1_Condition(in, out, s)
}

func autoConvert_v1alpha1_Field_To_porch_Field(in *Field, out *porch.Field, s conversion.Scope) error {
	out.Path = in.Path
	out.CurrentValue = in.CurrentValue
	out.ProposedValue = in.ProposedValue
	return nil
}

// Convert_v1alpha1_Field_To_porch_Field is an autogenerated conversion function.
func Convert_v1alpha1_Field_To_porch_Field(in *Field, out *porch.Field, s conversion.Scope) error {
	return autoConvert_v1alpha1_Field_To_porch_Field(in, out, s)
}

func autoConvert_porch_Field_To_v1alpha1_Field(in *porch.Field, out *Field, s conversion.Scope) error {
	out.Path = in.Path
	out.CurrentValue = in.CurrentValue
	out.ProposedValue = in.ProposedValue
	return nil
}

// Convert_porch_Field_To_v1alpha1_Field is an autogenerated conversion function.
func Convert_porch_Field_To_v1alpha1_Field(in *porch.Field, out *Field, s conversion.Scope) error {
	return autoConvert_porch_Field_To_v1alpha1_Field(in, out, s)
}

func autoConvert_v1alpha1_File_To_porch_File(in *File, out *porch.File, s conversion.Scope) error {
	out.Path = in.Path
	out.Index = in.Index
	return nil
}

// Convert_v1alpha1_File_To_porch_File is an autogenerated conversion function.
func Convert_v1alpha1_File_To_porch_File(in *File, out *porch.File, s conversion.Scope) error {
	return autoConvert_v1alpha1_File_To_porch_File(in, out, s)
}

func autoConvert_porch_File_To_v1alpha1_File(in *porch.File, out *File, s conversion.Scope) error {
	out.Path = in.Path
	out.Index = in.Index
	return nil
}

// Convert_porch_File_To_v1alpha1_File is an autogenerated conversion function.
func Convert_porch_File_To_v1alpha1_File(in *porch.File, out *File, s conversion.Scope) error {
	return autoConvert_porch_File_To_v1alpha1_File(in, out, s)
}

func autoConvert_v1alpha1_Function_To_porch_Function(in *Function, out *porch.Function, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_FunctionSpec_To_porch_FunctionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_FunctionStatus_To_porch_FunctionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Function_To_porch_Function is an autogenerated conversion function.
func Convert_v1alpha1_Function_To_porch_Function(in *Function, out *porch.Function, s conversion.Scope) error {
	return autoConvert_v1alpha1_Function_To_porch_Function(in, out, s)
}

func autoConvert_porch_Function_To_v1alpha1_Function(in *porch.Function, out *Function, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_porch_FunctionSpec_To_v1alpha1_FunctionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_porch_FunctionStatus_To_v1alpha1_FunctionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_porch_Function_To_v1alpha1_Function is an autogenerated conversion function.
func Convert_porch_Function_To_v1alpha1_Function(in *porch.Function, out *Function, s conversion.Scope) error {
	return autoConvert_porch_Function_To_v1alpha1_Function(in, out, s)
}

func autoConvert_v1alpha1_FunctionConfig_To_porch_FunctionConfig(in *FunctionConfig, out *porch.FunctionConfig, s conversion.Scope) error {
	out.RequiredFields = *(*[]string)(unsafe.Pointer(&in.RequiredFields))
	return nil
}

// Convert_v1alpha1_FunctionConfig_To_porch_FunctionConfig is an autogenerated conversion function.
func Convert_v1alpha1_FunctionConfig_To_porch_FunctionConfig(in *FunctionConfig, out *porch.FunctionConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_FunctionConfig_To_porch_FunctionConfig(in, out, s)
}

func autoConvert_porch_FunctionConfig_To_v1alpha1_FunctionConfig(in *porch.FunctionConfig, out *FunctionConfig, s conversion.Scope) error {
	out.RequiredFields = *(*[]string)(unsafe.Pointer(&in.RequiredFields))
	return nil
}

// Convert_porch_FunctionConfig_To_v1alpha1_FunctionConfig is an autogenerated conversion function.
func Convert_porch_FunctionConfig_To_v1alpha1_FunctionConfig(in *porch.FunctionConfig, out *FunctionConfig, s conversion.Scope) error {
	return autoConvert_porch_FunctionConfig_To_v1alpha1_FunctionConfig(in, out, s)
}

func autoConvert_v1alpha1_FunctionEvalTaskSpec_To_porch_FunctionEvalTaskSpec(in *FunctionEvalTaskSpec, out *porch.FunctionEvalTaskSpec, s conversion.Scope) error {
	out.Subpackage = in.Subpackage
	out.Image = in.Image
	out.FunctionRef = (*porch.FunctionRef)(unsafe.Pointer(in.FunctionRef))
	out.ConfigMap = *(*map[string]string)(unsafe.Pointer(&in.ConfigMap))
	out.Config = in.Config
	out.IncludeMetaResources = in.IncludeMetaResources
	out.EnableNetwork = in.EnableNetwork
	if err := Convert_v1alpha1_Selector_To_porch_Selector(&in.Match, &out.Match, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_FunctionEvalTaskSpec_To_porch_FunctionEvalTaskSpec is an autogenerated conversion function.
func Convert_v1alpha1_FunctionEvalTaskSpec_To_porch_FunctionEvalTaskSpec(in *FunctionEvalTaskSpec, out *porch.FunctionEvalTaskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_FunctionEvalTaskSpec_To_porch_FunctionEvalTaskSpec(in, out, s)
}

func autoConvert_porch_FunctionEvalTaskSpec_To_v1alpha1_FunctionEvalTaskSpec(in *porch.FunctionEvalTaskSpec, out *FunctionEvalTaskSpec, s conversion.Scope) error {
	out.Subpackage = in.Subpackage
	out.Image = in.Image
	out.FunctionRef = (*FunctionRef)(unsafe.Pointer(in.FunctionRef))
	out.ConfigMap = *(*map[string]string)(unsafe.Pointer(&in.ConfigMap))
	out.Config = in.Config
	out.IncludeMetaResources = in.IncludeMetaResources
	out.EnableNetwork = in.EnableNetwork
	if err := Convert_porch_Selector_To_v1alpha1_Selector(&in.Match, &out.Match, s); err != nil {
		return err
	}
	return nil
}

// Convert_porch_FunctionEvalTaskSpec_To_v1alpha1_FunctionEvalTaskSpec is an autogenerated conversion function.
func Convert_porch_FunctionEvalTaskSpec_To_v1alpha1_FunctionEvalTaskSpec(in *porch.FunctionEvalTaskSpec, out *FunctionEvalTaskSpec, s conversion.Scope) error {
	return autoConvert_porch_FunctionEvalTaskSpec_To_v1alpha1_FunctionEvalTaskSpec(in, out, s)
}

func autoConvert_v1alpha1_FunctionList_To_porch_FunctionList(in *FunctionList, out *porch.FunctionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]porch.Function)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_FunctionList_To_porch_FunctionList is an autogenerated conversion function.
func Convert_v1alpha1_FunctionList_To_porch_FunctionList(in *FunctionList, out *porch.FunctionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_FunctionList_To_porch_FunctionList(in, out, s)
}

func autoConvert_porch_FunctionList_To_v1alpha1_FunctionList(in *porch.FunctionList, out *FunctionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Function)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_porch_FunctionList_To_v1alpha1_FunctionList is an autogenerated conversion function.
func Convert_porch_FunctionList_To_v1alpha1_FunctionList(in *porch.FunctionList, out *FunctionList, s conversion.Scope) error {
	return autoConvert_porch_FunctionList_To_v1alpha1_FunctionList(in, out, s)
}

func autoConvert_v1alpha1_FunctionRef_To_porch_FunctionRef(in *FunctionRef, out *porch.FunctionRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_FunctionRef_To_porch_FunctionRef is an autogenerated conversion function.
func Convert_v1alpha1_FunctionRef_To_porch_FunctionRef(in *FunctionRef, out *porch.FunctionRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_FunctionRef_To_porch_FunctionRef(in, out, s)
}

func autoConvert_porch_FunctionRef_To_v1alpha1_FunctionRef(in *porch.FunctionRef, out *FunctionRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_porch_FunctionRef_To_v1alpha1_FunctionRef is an autogenerated conversion function.
func Convert_porch_FunctionRef_To_v1alpha1_FunctionRef(in *porch.FunctionRef, out *FunctionRef, s conversion.Scope) error {
	return autoConvert_porch_FunctionRef_To_v1alpha1_FunctionRef(in, out, s)
}

func autoConvert_v1alpha1_FunctionSpec_To_porch_FunctionSpec(in *FunctionSpec, out *porch.FunctionSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_v1alpha1_RepositoryRef_To_porch_RepositoryRef(&in.RepositoryRef, &out.RepositoryRef, s); err != nil {
		return err
	}
	out.FunctionTypes = *(*[]porch.FunctionType)(unsafe.Pointer(&in.FunctionTypes))
	out.FunctionConfigs = *(*[]porch.FunctionConfig)(unsafe.Pointer(&in.FunctionConfigs))
	out.Keywords = *(*[]string)(unsafe.Pointer(&in.Keywords))
	out.Description = in.Description
	out.DocumentationUrl = in.DocumentationUrl
	return nil
}

// Convert_v1alpha1_FunctionSpec_To_porch_FunctionSpec is an autogenerated conversion function.
func Convert_v1alpha1_FunctionSpec_To_porch_FunctionSpec(in *FunctionSpec, out *porch.FunctionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_FunctionSpec_To_porch_FunctionSpec(in, out, s)
}

func autoConvert_porch_FunctionSpec_To_v1alpha1_FunctionSpec(in *porch.FunctionSpec, out *FunctionSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_porch_RepositoryRef_To_v1alpha1_RepositoryRef(&in.RepositoryRef, &out.RepositoryRef, s); err != nil {
		return err
	}
	out.FunctionTypes = *(*[]FunctionType)(unsafe.Pointer(&in.FunctionTypes))
	out.FunctionConfigs = *(*[]FunctionConfig)(unsafe.Pointer(&in.FunctionConfigs))
	out.Keywords = *(*[]string)(unsafe.Pointer(&in.Keywords))
	out.Description = in.Description
	out.DocumentationUrl = in.DocumentationUrl
	return nil
}

// Convert_porch_FunctionSpec_To_v1alpha1_FunctionSpec is an autogenerated conversion function.
func Convert_porch_FunctionSpec_To_v1alpha1_FunctionSpec(in *porch.FunctionSpec, out *FunctionSpec, s conversion.Scope) error {
	return autoConvert_porch_FunctionSpec_To_v1alpha1_FunctionSpec(in, out, s)
}

func autoConvert_v1alpha1_FunctionStatus_To_porch_FunctionStatus(in *FunctionStatus, out *porch.FunctionStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_FunctionStatus_To_porch_FunctionStatus is an autogenerated conversion function.
func Convert_v1alpha1_FunctionStatus_To_porch_FunctionStatus(in *FunctionStatus, out *porch.FunctionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_FunctionStatus_To_porch_FunctionStatus(in, out, s)
}

func autoConvert_porch_FunctionStatus_To_v1alpha1_FunctionStatus(in *porch.FunctionStatus, out *FunctionStatus, s conversion.Scope) error {
	return nil
}

// Convert_porch_FunctionStatus_To_v1alpha1_FunctionStatus is an autogenerated conversion function.
func Convert_porch_FunctionStatus_To_v1alpha1_FunctionStatus(in *porch.FunctionStatus, out *FunctionStatus, s conversion.Scope) error {
	return autoConvert_porch_FunctionStatus_To_v1alpha1_FunctionStatus(in, out, s)
}

func autoConvert_v1alpha1_GitLock_To_porch_GitLock(in *GitLock, out *porch.GitLock, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Directory = in.Directory
	out.Ref = in.Ref
	out.Commit = in.Commit
	return nil
}

// Convert_v1alpha1_GitLock_To_porch_GitLock is an autogenerated conversion function.
func Convert_v1alpha1_GitLock_To_porch_GitLock(in *GitLock, out *porch.GitLock, s conversion.Scope) error {
	return autoConvert_v1alpha1_GitLock_To_porch_GitLock(in, out, s)
}

func autoConvert_porch_GitLock_To_v1alpha1_GitLock(in *porch.GitLock, out *GitLock, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Directory = in.Directory
	out.Ref = in.Ref
	out.Commit = in.Commit
	return nil
}

// Convert_porch_GitLock_To_v1alpha1_GitLock is an autogenerated conversion function.
func Convert_porch_GitLock_To_v1alpha1_GitLock(in *porch.GitLock, out *GitLock, s conversion.Scope) error {
	return autoConvert_porch_GitLock_To_v1alpha1_GitLock(in, out, s)
}

func autoConvert_v1alpha1_GitPorchPkg_To_porch_GitPorchPkg(in *GitPorchPkg, out *porch.GitPorchPkg, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Ref = in.Ref
	out.Directory = in.Directory
	if err := Convert_v1alpha1_SecretRef_To_porch_SecretRef(&in.SecretRef, &out.SecretRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_GitPorchPkg_To_porch_GitPorchPkg is an autogenerated conversion function.
func Convert_v1alpha1_GitPorchPkg_To_porch_GitPorchPkg(in *GitPorchPkg, out *porch.GitPorchPkg, s conversion.Scope) error {
	return autoConvert_v1alpha1_GitPorchPkg_To_porch_GitPorchPkg(in, out, s)
}

func autoConvert_porch_GitPorchPkg_To_v1alpha1_GitPorchPkg(in *porch.GitPorchPkg, out *GitPorchPkg, s conversion.Scope) error {
	out.Repo = in.Repo
	out.Ref = in.Ref
	out.Directory = in.Directory
	if err := Convert_porch_SecretRef_To_v1alpha1_SecretRef(&in.SecretRef, &out.SecretRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_porch_GitPorchPkg_To_v1alpha1_GitPorchPkg is an autogenerated conversion function.
func Convert_porch_GitPorchPkg_To_v1alpha1_GitPorchPkg(in *porch.GitPorchPkg, out *GitPorchPkg, s conversion.Scope) error {
	return autoConvert_porch_GitPorchPkg_To_v1alpha1_GitPorchPkg(in, out, s)
}

func autoConvert_v1alpha1_NameMeta_To_porch_NameMeta(in *NameMeta, out *porch.NameMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_NameMeta_To_porch_NameMeta is an autogenerated conversion function.
func Convert_v1alpha1_NameMeta_To_porch_NameMeta(in *NameMeta, out *porch.NameMeta, s conversion.Scope) error {
	return autoConvert_v1alpha1_NameMeta_To_porch_NameMeta(in, out, s)
}

func autoConvert_porch_NameMeta_To_v1alpha1_NameMeta(in *porch.NameMeta, out *NameMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_porch_NameMeta_To_v1alpha1_NameMeta is an autogenerated conversion function.
func Convert_porch_NameMeta_To_v1alpha1_NameMeta(in *porch.NameMeta, out *NameMeta, s conversion.Scope) error {
	return autoConvert_porch_NameMeta_To_v1alpha1_NameMeta(in, out, s)
}

func autoConvert_v1alpha1_OciPorchPkg_To_porch_OciPorchPkg(in *OciPorchPkg, out *porch.OciPorchPkg, s conversion.Scope) error {
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_OciPorchPkg_To_porch_OciPorchPkg is an autogenerated conversion function.
func Convert_v1alpha1_OciPorchPkg_To_porch_OciPorchPkg(in *OciPorchPkg, out *porch.OciPorchPkg, s conversion.Scope) error {
	return autoConvert_v1alpha1_OciPorchPkg_To_porch_OciPorchPkg(in, out, s)
}

func autoConvert_porch_OciPorchPkg_To_v1alpha1_OciPorchPkg(in *porch.OciPorchPkg, out *OciPorchPkg, s conversion.Scope) error {
	out.Image = in.Image
	return nil
}

// Convert_porch_OciPorchPkg_To_v1alpha1_OciPorchPkg is an autogenerated conversion function.
func Convert_porch_OciPorchPkg_To_v1alpha1_OciPorchPkg(in *porch.OciPorchPkg, out *OciPorchPkg, s conversion.Scope) error {
	return autoConvert_porch_OciPorchPkg_To_v1alpha1_OciPorchPkg(in, out, s)
}

func autoConvert_v1alpha1_ParentReference_To_porch_ParentReference(in *ParentReference, out *porch.ParentReference, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ParentReference_To_porch_ParentReference is an autogenerated conversion function.
func Convert_v1alpha1_ParentReference_To_porch_ParentReference(in *ParentReference, out *porch.ParentReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ParentReference_To_porch_ParentReference(in, out, s)
}

func autoConvert_porch_ParentReference_To_v1alpha1_ParentReference(in *porch.ParentReference, out *ParentReference, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_porch_ParentReference_To_v1alpha1_ParentReference is an autogenerated conversion function.
func Convert_porch_ParentReference_To_v1alpha1_ParentReference(in *porch.ParentReference, out *ParentReference, s conversion.Scope) error {
	return autoConvert_porch_ParentReference_To_v1alpha1_ParentReference(in, out, s)
}

func autoConvert_v1alpha1_PatchSpec_To_porch_PatchSpec(in *PatchSpec, out *porch.PatchSpec, s conversion.Scope) error {
	out.File = in.File
	out.Contents = in.Contents
	out.PatchType = porch.PatchType(in.PatchType)
	return nil
}

// Convert_v1alpha1_PatchSpec_To_porch_PatchSpec is an autogenerated conversion function.
func Convert_v1alpha1_PatchSpec_To_porch_PatchSpec(in *PatchSpec, out *porch.PatchSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PatchSpec_To_porch_PatchSpec(in, out, s)
}

func autoConvert_porch_PatchSpec_To_v1alpha1_PatchSpec(in *porch.PatchSpec, out *PatchSpec, s conversion.Scope) error {
	out.File = in.File
	out.Contents = in.Contents
	out.PatchType = PatchType(in.PatchType)
	return nil
}

// Convert_porch_PatchSpec_To_v1alpha1_PatchSpec is an autogenerated conversion function.
func Convert_porch_PatchSpec_To_v1alpha1_PatchSpec(in *porch.PatchSpec, out *PatchSpec, s conversion.Scope) error {
	return autoConvert_porch_PatchSpec_To_v1alpha1_PatchSpec(in, out, s)
}

func autoConvert_v1alpha1_PorchPkg_To_porch_PorchPkg(in *PorchPkg, out *porch.PorchPkg, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PorchPkgSpec_To_porch_PorchPkgSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PorchPkgStatus_To_porch_PorchPkgStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PorchPkg_To_porch_PorchPkg is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkg_To_porch_PorchPkg(in *PorchPkg, out *porch.PorchPkg, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkg_To_porch_PorchPkg(in, out, s)
}

func autoConvert_porch_PorchPkg_To_v1alpha1_PorchPkg(in *porch.PorchPkg, out *PorchPkg, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_porch_PorchPkgSpec_To_v1alpha1_PorchPkgSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_porch_PorchPkgStatus_To_v1alpha1_PorchPkgStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_porch_PorchPkg_To_v1alpha1_PorchPkg is an autogenerated conversion function.
func Convert_porch_PorchPkg_To_v1alpha1_PorchPkg(in *porch.PorchPkg, out *PorchPkg, s conversion.Scope) error {
	return autoConvert_porch_PorchPkg_To_v1alpha1_PorchPkg(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgCloneTaskSpec_To_porch_PorchPkgCloneTaskSpec(in *PorchPkgCloneTaskSpec, out *porch.PorchPkgCloneTaskSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_UpstreamPorchPkg_To_porch_UpstreamPorchPkg(&in.Upstream, &out.Upstream, s); err != nil {
		return err
	}
	out.Strategy = porch.PorchPkgMergeStrategy(in.Strategy)
	return nil
}

// Convert_v1alpha1_PorchPkgCloneTaskSpec_To_porch_PorchPkgCloneTaskSpec is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgCloneTaskSpec_To_porch_PorchPkgCloneTaskSpec(in *PorchPkgCloneTaskSpec, out *porch.PorchPkgCloneTaskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgCloneTaskSpec_To_porch_PorchPkgCloneTaskSpec(in, out, s)
}

func autoConvert_porch_PorchPkgCloneTaskSpec_To_v1alpha1_PorchPkgCloneTaskSpec(in *porch.PorchPkgCloneTaskSpec, out *PorchPkgCloneTaskSpec, s conversion.Scope) error {
	if err := Convert_porch_UpstreamPorchPkg_To_v1alpha1_UpstreamPorchPkg(&in.Upstream, &out.Upstream, s); err != nil {
		return err
	}
	out.Strategy = PorchPkgMergeStrategy(in.Strategy)
	return nil
}

// Convert_porch_PorchPkgCloneTaskSpec_To_v1alpha1_PorchPkgCloneTaskSpec is an autogenerated conversion function.
func Convert_porch_PorchPkgCloneTaskSpec_To_v1alpha1_PorchPkgCloneTaskSpec(in *porch.PorchPkgCloneTaskSpec, out *PorchPkgCloneTaskSpec, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgCloneTaskSpec_To_v1alpha1_PorchPkgCloneTaskSpec(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgEditTaskSpec_To_porch_PorchPkgEditTaskSpec(in *PorchPkgEditTaskSpec, out *porch.PorchPkgEditTaskSpec, s conversion.Scope) error {
	out.Source = (*porch.PorchPkgRevisionRef)(unsafe.Pointer(in.Source))
	return nil
}

// Convert_v1alpha1_PorchPkgEditTaskSpec_To_porch_PorchPkgEditTaskSpec is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgEditTaskSpec_To_porch_PorchPkgEditTaskSpec(in *PorchPkgEditTaskSpec, out *porch.PorchPkgEditTaskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgEditTaskSpec_To_porch_PorchPkgEditTaskSpec(in, out, s)
}

func autoConvert_porch_PorchPkgEditTaskSpec_To_v1alpha1_PorchPkgEditTaskSpec(in *porch.PorchPkgEditTaskSpec, out *PorchPkgEditTaskSpec, s conversion.Scope) error {
	out.Source = (*PorchPkgRevisionRef)(unsafe.Pointer(in.Source))
	return nil
}

// Convert_porch_PorchPkgEditTaskSpec_To_v1alpha1_PorchPkgEditTaskSpec is an autogenerated conversion function.
func Convert_porch_PorchPkgEditTaskSpec_To_v1alpha1_PorchPkgEditTaskSpec(in *porch.PorchPkgEditTaskSpec, out *PorchPkgEditTaskSpec, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgEditTaskSpec_To_v1alpha1_PorchPkgEditTaskSpec(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgInitTaskSpec_To_porch_PorchPkgInitTaskSpec(in *PorchPkgInitTaskSpec, out *porch.PorchPkgInitTaskSpec, s conversion.Scope) error {
	out.Subpackage = in.Subpackage
	out.Description = in.Description
	out.Keywords = *(*[]string)(unsafe.Pointer(&in.Keywords))
	out.Site = in.Site
	return nil
}

// Convert_v1alpha1_PorchPkgInitTaskSpec_To_porch_PorchPkgInitTaskSpec is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgInitTaskSpec_To_porch_PorchPkgInitTaskSpec(in *PorchPkgInitTaskSpec, out *porch.PorchPkgInitTaskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgInitTaskSpec_To_porch_PorchPkgInitTaskSpec(in, out, s)
}

func autoConvert_porch_PorchPkgInitTaskSpec_To_v1alpha1_PorchPkgInitTaskSpec(in *porch.PorchPkgInitTaskSpec, out *PorchPkgInitTaskSpec, s conversion.Scope) error {
	out.Subpackage = in.Subpackage
	out.Description = in.Description
	out.Keywords = *(*[]string)(unsafe.Pointer(&in.Keywords))
	out.Site = in.Site
	return nil
}

// Convert_porch_PorchPkgInitTaskSpec_To_v1alpha1_PorchPkgInitTaskSpec is an autogenerated conversion function.
func Convert_porch_PorchPkgInitTaskSpec_To_v1alpha1_PorchPkgInitTaskSpec(in *porch.PorchPkgInitTaskSpec, out *PorchPkgInitTaskSpec, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgInitTaskSpec_To_v1alpha1_PorchPkgInitTaskSpec(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgList_To_porch_PorchPkgList(in *PorchPkgList, out *porch.PorchPkgList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]porch.PorchPkg)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PorchPkgList_To_porch_PorchPkgList is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgList_To_porch_PorchPkgList(in *PorchPkgList, out *porch.PorchPkgList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgList_To_porch_PorchPkgList(in, out, s)
}

func autoConvert_porch_PorchPkgList_To_v1alpha1_PorchPkgList(in *porch.PorchPkgList, out *PorchPkgList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PorchPkg)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_porch_PorchPkgList_To_v1alpha1_PorchPkgList is an autogenerated conversion function.
func Convert_porch_PorchPkgList_To_v1alpha1_PorchPkgList(in *porch.PorchPkgList, out *PorchPkgList, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgList_To_v1alpha1_PorchPkgList(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgPatchTaskSpec_To_porch_PorchPkgPatchTaskSpec(in *PorchPkgPatchTaskSpec, out *porch.PorchPkgPatchTaskSpec, s conversion.Scope) error {
	out.Patches = *(*[]porch.PatchSpec)(unsafe.Pointer(&in.Patches))
	return nil
}

// Convert_v1alpha1_PorchPkgPatchTaskSpec_To_porch_PorchPkgPatchTaskSpec is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgPatchTaskSpec_To_porch_PorchPkgPatchTaskSpec(in *PorchPkgPatchTaskSpec, out *porch.PorchPkgPatchTaskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgPatchTaskSpec_To_porch_PorchPkgPatchTaskSpec(in, out, s)
}

func autoConvert_porch_PorchPkgPatchTaskSpec_To_v1alpha1_PorchPkgPatchTaskSpec(in *porch.PorchPkgPatchTaskSpec, out *PorchPkgPatchTaskSpec, s conversion.Scope) error {
	out.Patches = *(*[]PatchSpec)(unsafe.Pointer(&in.Patches))
	return nil
}

// Convert_porch_PorchPkgPatchTaskSpec_To_v1alpha1_PorchPkgPatchTaskSpec is an autogenerated conversion function.
func Convert_porch_PorchPkgPatchTaskSpec_To_v1alpha1_PorchPkgPatchTaskSpec(in *porch.PorchPkgPatchTaskSpec, out *PorchPkgPatchTaskSpec, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgPatchTaskSpec_To_v1alpha1_PorchPkgPatchTaskSpec(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgRevision_To_porch_PorchPkgRevision(in *PorchPkgRevision, out *porch.PorchPkgRevision, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PorchPkgRevisionSpec_To_porch_PorchPkgRevisionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PorchPkgRevisionStatus_To_porch_PorchPkgRevisionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PorchPkgRevision_To_porch_PorchPkgRevision is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgRevision_To_porch_PorchPkgRevision(in *PorchPkgRevision, out *porch.PorchPkgRevision, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgRevision_To_porch_PorchPkgRevision(in, out, s)
}

func autoConvert_porch_PorchPkgRevision_To_v1alpha1_PorchPkgRevision(in *porch.PorchPkgRevision, out *PorchPkgRevision, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_porch_PorchPkgRevisionSpec_To_v1alpha1_PorchPkgRevisionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_porch_PorchPkgRevisionStatus_To_v1alpha1_PorchPkgRevisionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_porch_PorchPkgRevision_To_v1alpha1_PorchPkgRevision is an autogenerated conversion function.
func Convert_porch_PorchPkgRevision_To_v1alpha1_PorchPkgRevision(in *porch.PorchPkgRevision, out *PorchPkgRevision, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgRevision_To_v1alpha1_PorchPkgRevision(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgRevisionList_To_porch_PorchPkgRevisionList(in *PorchPkgRevisionList, out *porch.PorchPkgRevisionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]porch.PorchPkgRevision)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PorchPkgRevisionList_To_porch_PorchPkgRevisionList is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgRevisionList_To_porch_PorchPkgRevisionList(in *PorchPkgRevisionList, out *porch.PorchPkgRevisionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgRevisionList_To_porch_PorchPkgRevisionList(in, out, s)
}

func autoConvert_porch_PorchPkgRevisionList_To_v1alpha1_PorchPkgRevisionList(in *porch.PorchPkgRevisionList, out *PorchPkgRevisionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PorchPkgRevision)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_porch_PorchPkgRevisionList_To_v1alpha1_PorchPkgRevisionList is an autogenerated conversion function.
func Convert_porch_PorchPkgRevisionList_To_v1alpha1_PorchPkgRevisionList(in *porch.PorchPkgRevisionList, out *PorchPkgRevisionList, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgRevisionList_To_v1alpha1_PorchPkgRevisionList(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgRevisionRef_To_porch_PorchPkgRevisionRef(in *PorchPkgRevisionRef, out *porch.PorchPkgRevisionRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_PorchPkgRevisionRef_To_porch_PorchPkgRevisionRef is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgRevisionRef_To_porch_PorchPkgRevisionRef(in *PorchPkgRevisionRef, out *porch.PorchPkgRevisionRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgRevisionRef_To_porch_PorchPkgRevisionRef(in, out, s)
}

func autoConvert_porch_PorchPkgRevisionRef_To_v1alpha1_PorchPkgRevisionRef(in *porch.PorchPkgRevisionRef, out *PorchPkgRevisionRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_porch_PorchPkgRevisionRef_To_v1alpha1_PorchPkgRevisionRef is an autogenerated conversion function.
func Convert_porch_PorchPkgRevisionRef_To_v1alpha1_PorchPkgRevisionRef(in *porch.PorchPkgRevisionRef, out *PorchPkgRevisionRef, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgRevisionRef_To_v1alpha1_PorchPkgRevisionRef(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgRevisionResources_To_porch_PorchPkgRevisionResources(in *PorchPkgRevisionResources, out *porch.PorchPkgRevisionResources, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PorchPkgRevisionResourcesSpec_To_porch_PorchPkgRevisionResourcesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PorchPkgRevisionResourcesStatus_To_porch_PorchPkgRevisionResourcesStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PorchPkgRevisionResources_To_porch_PorchPkgRevisionResources is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgRevisionResources_To_porch_PorchPkgRevisionResources(in *PorchPkgRevisionResources, out *porch.PorchPkgRevisionResources, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgRevisionResources_To_porch_PorchPkgRevisionResources(in, out, s)
}

func autoConvert_porch_PorchPkgRevisionResources_To_v1alpha1_PorchPkgRevisionResources(in *porch.PorchPkgRevisionResources, out *PorchPkgRevisionResources, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_porch_PorchPkgRevisionResourcesSpec_To_v1alpha1_PorchPkgRevisionResourcesSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_porch_PorchPkgRevisionResourcesStatus_To_v1alpha1_PorchPkgRevisionResourcesStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_porch_PorchPkgRevisionResources_To_v1alpha1_PorchPkgRevisionResources is an autogenerated conversion function.
func Convert_porch_PorchPkgRevisionResources_To_v1alpha1_PorchPkgRevisionResources(in *porch.PorchPkgRevisionResources, out *PorchPkgRevisionResources, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgRevisionResources_To_v1alpha1_PorchPkgRevisionResources(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgRevisionResourcesList_To_porch_PorchPkgRevisionResourcesList(in *PorchPkgRevisionResourcesList, out *porch.PorchPkgRevisionResourcesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]porch.PorchPkgRevisionResources)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PorchPkgRevisionResourcesList_To_porch_PorchPkgRevisionResourcesList is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgRevisionResourcesList_To_porch_PorchPkgRevisionResourcesList(in *PorchPkgRevisionResourcesList, out *porch.PorchPkgRevisionResourcesList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgRevisionResourcesList_To_porch_PorchPkgRevisionResourcesList(in, out, s)
}

func autoConvert_porch_PorchPkgRevisionResourcesList_To_v1alpha1_PorchPkgRevisionResourcesList(in *porch.PorchPkgRevisionResourcesList, out *PorchPkgRevisionResourcesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PorchPkgRevisionResources)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_porch_PorchPkgRevisionResourcesList_To_v1alpha1_PorchPkgRevisionResourcesList is an autogenerated conversion function.
func Convert_porch_PorchPkgRevisionResourcesList_To_v1alpha1_PorchPkgRevisionResourcesList(in *porch.PorchPkgRevisionResourcesList, out *PorchPkgRevisionResourcesList, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgRevisionResourcesList_To_v1alpha1_PorchPkgRevisionResourcesList(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgRevisionResourcesSpec_To_porch_PorchPkgRevisionResourcesSpec(in *PorchPkgRevisionResourcesSpec, out *porch.PorchPkgRevisionResourcesSpec, s conversion.Scope) error {
	out.PorchPkgName = in.PorchPkgName
	out.WorkspaceName = porch.WorkspaceName(in.WorkspaceName)
	out.Revision = in.Revision
	out.RepositoryName = in.RepositoryName
	out.Resources = *(*map[string]string)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1alpha1_PorchPkgRevisionResourcesSpec_To_porch_PorchPkgRevisionResourcesSpec is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgRevisionResourcesSpec_To_porch_PorchPkgRevisionResourcesSpec(in *PorchPkgRevisionResourcesSpec, out *porch.PorchPkgRevisionResourcesSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgRevisionResourcesSpec_To_porch_PorchPkgRevisionResourcesSpec(in, out, s)
}

func autoConvert_porch_PorchPkgRevisionResourcesSpec_To_v1alpha1_PorchPkgRevisionResourcesSpec(in *porch.PorchPkgRevisionResourcesSpec, out *PorchPkgRevisionResourcesSpec, s conversion.Scope) error {
	out.PorchPkgName = in.PorchPkgName
	out.WorkspaceName = WorkspaceName(in.WorkspaceName)
	out.Revision = in.Revision
	out.RepositoryName = in.RepositoryName
	out.Resources = *(*map[string]string)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_porch_PorchPkgRevisionResourcesSpec_To_v1alpha1_PorchPkgRevisionResourcesSpec is an autogenerated conversion function.
func Convert_porch_PorchPkgRevisionResourcesSpec_To_v1alpha1_PorchPkgRevisionResourcesSpec(in *porch.PorchPkgRevisionResourcesSpec, out *PorchPkgRevisionResourcesSpec, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgRevisionResourcesSpec_To_v1alpha1_PorchPkgRevisionResourcesSpec(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgRevisionResourcesStatus_To_porch_PorchPkgRevisionResourcesStatus(in *PorchPkgRevisionResourcesStatus, out *porch.PorchPkgRevisionResourcesStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_RenderStatus_To_porch_RenderStatus(&in.RenderStatus, &out.RenderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PorchPkgRevisionResourcesStatus_To_porch_PorchPkgRevisionResourcesStatus is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgRevisionResourcesStatus_To_porch_PorchPkgRevisionResourcesStatus(in *PorchPkgRevisionResourcesStatus, out *porch.PorchPkgRevisionResourcesStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgRevisionResourcesStatus_To_porch_PorchPkgRevisionResourcesStatus(in, out, s)
}

func autoConvert_porch_PorchPkgRevisionResourcesStatus_To_v1alpha1_PorchPkgRevisionResourcesStatus(in *porch.PorchPkgRevisionResourcesStatus, out *PorchPkgRevisionResourcesStatus, s conversion.Scope) error {
	if err := Convert_porch_RenderStatus_To_v1alpha1_RenderStatus(&in.RenderStatus, &out.RenderStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_porch_PorchPkgRevisionResourcesStatus_To_v1alpha1_PorchPkgRevisionResourcesStatus is an autogenerated conversion function.
func Convert_porch_PorchPkgRevisionResourcesStatus_To_v1alpha1_PorchPkgRevisionResourcesStatus(in *porch.PorchPkgRevisionResourcesStatus, out *PorchPkgRevisionResourcesStatus, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgRevisionResourcesStatus_To_v1alpha1_PorchPkgRevisionResourcesStatus(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgRevisionSpec_To_porch_PorchPkgRevisionSpec(in *PorchPkgRevisionSpec, out *porch.PorchPkgRevisionSpec, s conversion.Scope) error {
	out.PorchPkgName = in.PorchPkgName
	out.RepositoryName = in.RepositoryName
	out.WorkspaceName = porch.WorkspaceName(in.WorkspaceName)
	out.Revision = in.Revision
	out.Parent = (*porch.ParentReference)(unsafe.Pointer(in.Parent))
	out.Lifecycle = porch.PorchPkgRevisionLifecycle(in.Lifecycle)
	out.Tasks = *(*[]porch.Task)(unsafe.Pointer(&in.Tasks))
	out.ReadinessGates = *(*[]porch.ReadinessGate)(unsafe.Pointer(&in.ReadinessGates))
	return nil
}

// Convert_v1alpha1_PorchPkgRevisionSpec_To_porch_PorchPkgRevisionSpec is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgRevisionSpec_To_porch_PorchPkgRevisionSpec(in *PorchPkgRevisionSpec, out *porch.PorchPkgRevisionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgRevisionSpec_To_porch_PorchPkgRevisionSpec(in, out, s)
}

func autoConvert_porch_PorchPkgRevisionSpec_To_v1alpha1_PorchPkgRevisionSpec(in *porch.PorchPkgRevisionSpec, out *PorchPkgRevisionSpec, s conversion.Scope) error {
	out.PorchPkgName = in.PorchPkgName
	out.RepositoryName = in.RepositoryName
	out.WorkspaceName = WorkspaceName(in.WorkspaceName)
	out.Revision = in.Revision
	out.Parent = (*ParentReference)(unsafe.Pointer(in.Parent))
	out.Lifecycle = PorchPkgRevisionLifecycle(in.Lifecycle)
	out.Tasks = *(*[]Task)(unsafe.Pointer(&in.Tasks))
	out.ReadinessGates = *(*[]ReadinessGate)(unsafe.Pointer(&in.ReadinessGates))
	return nil
}

// Convert_porch_PorchPkgRevisionSpec_To_v1alpha1_PorchPkgRevisionSpec is an autogenerated conversion function.
func Convert_porch_PorchPkgRevisionSpec_To_v1alpha1_PorchPkgRevisionSpec(in *porch.PorchPkgRevisionSpec, out *PorchPkgRevisionSpec, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgRevisionSpec_To_v1alpha1_PorchPkgRevisionSpec(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgRevisionStatus_To_porch_PorchPkgRevisionStatus(in *PorchPkgRevisionStatus, out *porch.PorchPkgRevisionStatus, s conversion.Scope) error {
	out.UpstreamLock = (*porch.UpstreamLock)(unsafe.Pointer(in.UpstreamLock))
	out.PublishedBy = in.PublishedBy
	out.PublishedAt = in.PublishedAt
	out.Deployment = in.Deployment
	out.Conditions = *(*[]porch.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_PorchPkgRevisionStatus_To_porch_PorchPkgRevisionStatus is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgRevisionStatus_To_porch_PorchPkgRevisionStatus(in *PorchPkgRevisionStatus, out *porch.PorchPkgRevisionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgRevisionStatus_To_porch_PorchPkgRevisionStatus(in, out, s)
}

func autoConvert_porch_PorchPkgRevisionStatus_To_v1alpha1_PorchPkgRevisionStatus(in *porch.PorchPkgRevisionStatus, out *PorchPkgRevisionStatus, s conversion.Scope) error {
	out.UpstreamLock = (*UpstreamLock)(unsafe.Pointer(in.UpstreamLock))
	out.PublishedBy = in.PublishedBy
	out.PublishedAt = in.PublishedAt
	out.Deployment = in.Deployment
	out.Conditions = *(*[]Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_porch_PorchPkgRevisionStatus_To_v1alpha1_PorchPkgRevisionStatus is an autogenerated conversion function.
func Convert_porch_PorchPkgRevisionStatus_To_v1alpha1_PorchPkgRevisionStatus(in *porch.PorchPkgRevisionStatus, out *PorchPkgRevisionStatus, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgRevisionStatus_To_v1alpha1_PorchPkgRevisionStatus(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgSpec_To_porch_PorchPkgSpec(in *PorchPkgSpec, out *porch.PorchPkgSpec, s conversion.Scope) error {
	out.PorchPkgName = in.PorchPkgName
	out.RepositoryName = in.RepositoryName
	return nil
}

// Convert_v1alpha1_PorchPkgSpec_To_porch_PorchPkgSpec is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgSpec_To_porch_PorchPkgSpec(in *PorchPkgSpec, out *porch.PorchPkgSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgSpec_To_porch_PorchPkgSpec(in, out, s)
}

func autoConvert_porch_PorchPkgSpec_To_v1alpha1_PorchPkgSpec(in *porch.PorchPkgSpec, out *PorchPkgSpec, s conversion.Scope) error {
	out.PorchPkgName = in.PorchPkgName
	out.RepositoryName = in.RepositoryName
	return nil
}

// Convert_porch_PorchPkgSpec_To_v1alpha1_PorchPkgSpec is an autogenerated conversion function.
func Convert_porch_PorchPkgSpec_To_v1alpha1_PorchPkgSpec(in *porch.PorchPkgSpec, out *PorchPkgSpec, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgSpec_To_v1alpha1_PorchPkgSpec(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgStatus_To_porch_PorchPkgStatus(in *PorchPkgStatus, out *porch.PorchPkgStatus, s conversion.Scope) error {
	out.LatestRevision = in.LatestRevision
	return nil
}

// Convert_v1alpha1_PorchPkgStatus_To_porch_PorchPkgStatus is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgStatus_To_porch_PorchPkgStatus(in *PorchPkgStatus, out *porch.PorchPkgStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgStatus_To_porch_PorchPkgStatus(in, out, s)
}

func autoConvert_porch_PorchPkgStatus_To_v1alpha1_PorchPkgStatus(in *porch.PorchPkgStatus, out *PorchPkgStatus, s conversion.Scope) error {
	out.LatestRevision = in.LatestRevision
	return nil
}

// Convert_porch_PorchPkgStatus_To_v1alpha1_PorchPkgStatus is an autogenerated conversion function.
func Convert_porch_PorchPkgStatus_To_v1alpha1_PorchPkgStatus(in *porch.PorchPkgStatus, out *PorchPkgStatus, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgStatus_To_v1alpha1_PorchPkgStatus(in, out, s)
}

func autoConvert_v1alpha1_PorchPkgUpdateTaskSpec_To_porch_PorchPkgUpdateTaskSpec(in *PorchPkgUpdateTaskSpec, out *porch.PorchPkgUpdateTaskSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_UpstreamPorchPkg_To_porch_UpstreamPorchPkg(&in.Upstream, &out.Upstream, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PorchPkgUpdateTaskSpec_To_porch_PorchPkgUpdateTaskSpec is an autogenerated conversion function.
func Convert_v1alpha1_PorchPkgUpdateTaskSpec_To_porch_PorchPkgUpdateTaskSpec(in *PorchPkgUpdateTaskSpec, out *porch.PorchPkgUpdateTaskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PorchPkgUpdateTaskSpec_To_porch_PorchPkgUpdateTaskSpec(in, out, s)
}

func autoConvert_porch_PorchPkgUpdateTaskSpec_To_v1alpha1_PorchPkgUpdateTaskSpec(in *porch.PorchPkgUpdateTaskSpec, out *PorchPkgUpdateTaskSpec, s conversion.Scope) error {
	if err := Convert_porch_UpstreamPorchPkg_To_v1alpha1_UpstreamPorchPkg(&in.Upstream, &out.Upstream, s); err != nil {
		return err
	}
	return nil
}

// Convert_porch_PorchPkgUpdateTaskSpec_To_v1alpha1_PorchPkgUpdateTaskSpec is an autogenerated conversion function.
func Convert_porch_PorchPkgUpdateTaskSpec_To_v1alpha1_PorchPkgUpdateTaskSpec(in *porch.PorchPkgUpdateTaskSpec, out *PorchPkgUpdateTaskSpec, s conversion.Scope) error {
	return autoConvert_porch_PorchPkgUpdateTaskSpec_To_v1alpha1_PorchPkgUpdateTaskSpec(in, out, s)
}

func autoConvert_v1alpha1_ReadinessGate_To_porch_ReadinessGate(in *ReadinessGate, out *porch.ReadinessGate, s conversion.Scope) error {
	out.ConditionType = in.ConditionType
	return nil
}

// Convert_v1alpha1_ReadinessGate_To_porch_ReadinessGate is an autogenerated conversion function.
func Convert_v1alpha1_ReadinessGate_To_porch_ReadinessGate(in *ReadinessGate, out *porch.ReadinessGate, s conversion.Scope) error {
	return autoConvert_v1alpha1_ReadinessGate_To_porch_ReadinessGate(in, out, s)
}

func autoConvert_porch_ReadinessGate_To_v1alpha1_ReadinessGate(in *porch.ReadinessGate, out *ReadinessGate, s conversion.Scope) error {
	out.ConditionType = in.ConditionType
	return nil
}

// Convert_porch_ReadinessGate_To_v1alpha1_ReadinessGate is an autogenerated conversion function.
func Convert_porch_ReadinessGate_To_v1alpha1_ReadinessGate(in *porch.ReadinessGate, out *ReadinessGate, s conversion.Scope) error {
	return autoConvert_porch_ReadinessGate_To_v1alpha1_ReadinessGate(in, out, s)
}

func autoConvert_v1alpha1_RenderStatus_To_porch_RenderStatus(in *RenderStatus, out *porch.RenderStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_ResultList_To_porch_ResultList(&in.Result, &out.Result, s); err != nil {
		return err
	}
	out.Err = in.Err
	return nil
}

// Convert_v1alpha1_RenderStatus_To_porch_RenderStatus is an autogenerated conversion function.
func Convert_v1alpha1_RenderStatus_To_porch_RenderStatus(in *RenderStatus, out *porch.RenderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RenderStatus_To_porch_RenderStatus(in, out, s)
}

func autoConvert_porch_RenderStatus_To_v1alpha1_RenderStatus(in *porch.RenderStatus, out *RenderStatus, s conversion.Scope) error {
	if err := Convert_porch_ResultList_To_v1alpha1_ResultList(&in.Result, &out.Result, s); err != nil {
		return err
	}
	out.Err = in.Err
	return nil
}

// Convert_porch_RenderStatus_To_v1alpha1_RenderStatus is an autogenerated conversion function.
func Convert_porch_RenderStatus_To_v1alpha1_RenderStatus(in *porch.RenderStatus, out *RenderStatus, s conversion.Scope) error {
	return autoConvert_porch_RenderStatus_To_v1alpha1_RenderStatus(in, out, s)
}

func autoConvert_v1alpha1_RepositoryRef_To_porch_RepositoryRef(in *RepositoryRef, out *porch.RepositoryRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_RepositoryRef_To_porch_RepositoryRef is an autogenerated conversion function.
func Convert_v1alpha1_RepositoryRef_To_porch_RepositoryRef(in *RepositoryRef, out *porch.RepositoryRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepositoryRef_To_porch_RepositoryRef(in, out, s)
}

func autoConvert_porch_RepositoryRef_To_v1alpha1_RepositoryRef(in *porch.RepositoryRef, out *RepositoryRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_porch_RepositoryRef_To_v1alpha1_RepositoryRef is an autogenerated conversion function.
func Convert_porch_RepositoryRef_To_v1alpha1_RepositoryRef(in *porch.RepositoryRef, out *RepositoryRef, s conversion.Scope) error {
	return autoConvert_porch_RepositoryRef_To_v1alpha1_RepositoryRef(in, out, s)
}

func autoConvert_v1alpha1_ResourceIdentifier_To_porch_ResourceIdentifier(in *ResourceIdentifier, out *porch.ResourceIdentifier, s conversion.Scope) error {
	if err := Convert_v1alpha1_NameMeta_To_porch_NameMeta(&in.NameMeta, &out.NameMeta, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ResourceIdentifier_To_porch_ResourceIdentifier is an autogenerated conversion function.
func Convert_v1alpha1_ResourceIdentifier_To_porch_ResourceIdentifier(in *ResourceIdentifier, out *porch.ResourceIdentifier, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceIdentifier_To_porch_ResourceIdentifier(in, out, s)
}

func autoConvert_porch_ResourceIdentifier_To_v1alpha1_ResourceIdentifier(in *porch.ResourceIdentifier, out *ResourceIdentifier, s conversion.Scope) error {
	if err := Convert_porch_NameMeta_To_v1alpha1_NameMeta(&in.NameMeta, &out.NameMeta, s); err != nil {
		return err
	}
	return nil
}

// Convert_porch_ResourceIdentifier_To_v1alpha1_ResourceIdentifier is an autogenerated conversion function.
func Convert_porch_ResourceIdentifier_To_v1alpha1_ResourceIdentifier(in *porch.ResourceIdentifier, out *ResourceIdentifier, s conversion.Scope) error {
	return autoConvert_porch_ResourceIdentifier_To_v1alpha1_ResourceIdentifier(in, out, s)
}

func autoConvert_v1alpha1_Result_To_porch_Result(in *Result, out *porch.Result, s conversion.Scope) error {
	out.Image = in.Image
	out.ExecPath = in.ExecPath
	out.Stderr = in.Stderr
	out.ExitCode = in.ExitCode
	out.Results = *(*[]porch.ResultItem)(unsafe.Pointer(&in.Results))
	return nil
}

// Convert_v1alpha1_Result_To_porch_Result is an autogenerated conversion function.
func Convert_v1alpha1_Result_To_porch_Result(in *Result, out *porch.Result, s conversion.Scope) error {
	return autoConvert_v1alpha1_Result_To_porch_Result(in, out, s)
}

func autoConvert_porch_Result_To_v1alpha1_Result(in *porch.Result, out *Result, s conversion.Scope) error {
	out.Image = in.Image
	out.ExecPath = in.ExecPath
	out.Stderr = in.Stderr
	out.ExitCode = in.ExitCode
	out.Results = *(*[]ResultItem)(unsafe.Pointer(&in.Results))
	return nil
}

// Convert_porch_Result_To_v1alpha1_Result is an autogenerated conversion function.
func Convert_porch_Result_To_v1alpha1_Result(in *porch.Result, out *Result, s conversion.Scope) error {
	return autoConvert_porch_Result_To_v1alpha1_Result(in, out, s)
}

func autoConvert_v1alpha1_ResultItem_To_porch_ResultItem(in *ResultItem, out *porch.ResultItem, s conversion.Scope) error {
	out.Message = in.Message
	out.Severity = in.Severity
	out.ResourceRef = (*porch.ResourceIdentifier)(unsafe.Pointer(in.ResourceRef))
	out.Field = (*porch.Field)(unsafe.Pointer(in.Field))
	out.File = (*porch.File)(unsafe.Pointer(in.File))
	out.Tags = *(*map[string]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha1_ResultItem_To_porch_ResultItem is an autogenerated conversion function.
func Convert_v1alpha1_ResultItem_To_porch_ResultItem(in *ResultItem, out *porch.ResultItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResultItem_To_porch_ResultItem(in, out, s)
}

func autoConvert_porch_ResultItem_To_v1alpha1_ResultItem(in *porch.ResultItem, out *ResultItem, s conversion.Scope) error {
	out.Message = in.Message
	out.Severity = in.Severity
	out.ResourceRef = (*ResourceIdentifier)(unsafe.Pointer(in.ResourceRef))
	out.Field = (*Field)(unsafe.Pointer(in.Field))
	out.File = (*File)(unsafe.Pointer(in.File))
	out.Tags = *(*map[string]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_porch_ResultItem_To_v1alpha1_ResultItem is an autogenerated conversion function.
func Convert_porch_ResultItem_To_v1alpha1_ResultItem(in *porch.ResultItem, out *ResultItem, s conversion.Scope) error {
	return autoConvert_porch_ResultItem_To_v1alpha1_ResultItem(in, out, s)
}

func autoConvert_v1alpha1_ResultList_To_porch_ResultList(in *ResultList, out *porch.ResultList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ExitCode = in.ExitCode
	out.Items = *(*[]*porch.Result)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ResultList_To_porch_ResultList is an autogenerated conversion function.
func Convert_v1alpha1_ResultList_To_porch_ResultList(in *ResultList, out *porch.ResultList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResultList_To_porch_ResultList(in, out, s)
}

func autoConvert_porch_ResultList_To_v1alpha1_ResultList(in *porch.ResultList, out *ResultList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ExitCode = in.ExitCode
	out.Items = *(*[]*Result)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_porch_ResultList_To_v1alpha1_ResultList is an autogenerated conversion function.
func Convert_porch_ResultList_To_v1alpha1_ResultList(in *porch.ResultList, out *ResultList, s conversion.Scope) error {
	return autoConvert_porch_ResultList_To_v1alpha1_ResultList(in, out, s)
}

func autoConvert_v1alpha1_SecretRef_To_porch_SecretRef(in *SecretRef, out *porch.SecretRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_SecretRef_To_porch_SecretRef is an autogenerated conversion function.
func Convert_v1alpha1_SecretRef_To_porch_SecretRef(in *SecretRef, out *porch.SecretRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretRef_To_porch_SecretRef(in, out, s)
}

func autoConvert_porch_SecretRef_To_v1alpha1_SecretRef(in *porch.SecretRef, out *SecretRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_porch_SecretRef_To_v1alpha1_SecretRef is an autogenerated conversion function.
func Convert_porch_SecretRef_To_v1alpha1_SecretRef(in *porch.SecretRef, out *SecretRef, s conversion.Scope) error {
	return autoConvert_porch_SecretRef_To_v1alpha1_SecretRef(in, out, s)
}

func autoConvert_v1alpha1_Selector_To_porch_Selector(in *Selector, out *porch.Selector, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_Selector_To_porch_Selector is an autogenerated conversion function.
func Convert_v1alpha1_Selector_To_porch_Selector(in *Selector, out *porch.Selector, s conversion.Scope) error {
	return autoConvert_v1alpha1_Selector_To_porch_Selector(in, out, s)
}

func autoConvert_porch_Selector_To_v1alpha1_Selector(in *porch.Selector, out *Selector, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_porch_Selector_To_v1alpha1_Selector is an autogenerated conversion function.
func Convert_porch_Selector_To_v1alpha1_Selector(in *porch.Selector, out *Selector, s conversion.Scope) error {
	return autoConvert_porch_Selector_To_v1alpha1_Selector(in, out, s)
}

func autoConvert_v1alpha1_Task_To_porch_Task(in *Task, out *porch.Task, s conversion.Scope) error {
	out.Type = porch.TaskType(in.Type)
	out.Init = (*porch.PorchPkgInitTaskSpec)(unsafe.Pointer(in.Init))
	out.Clone = (*porch.PorchPkgCloneTaskSpec)(unsafe.Pointer(in.Clone))
	out.Patch = (*porch.PorchPkgPatchTaskSpec)(unsafe.Pointer(in.Patch))
	out.Edit = (*porch.PorchPkgEditTaskSpec)(unsafe.Pointer(in.Edit))
	out.Eval = (*porch.FunctionEvalTaskSpec)(unsafe.Pointer(in.Eval))
	out.Update = (*porch.PorchPkgUpdateTaskSpec)(unsafe.Pointer(in.Update))
	return nil
}

// Convert_v1alpha1_Task_To_porch_Task is an autogenerated conversion function.
func Convert_v1alpha1_Task_To_porch_Task(in *Task, out *porch.Task, s conversion.Scope) error {
	return autoConvert_v1alpha1_Task_To_porch_Task(in, out, s)
}

func autoConvert_porch_Task_To_v1alpha1_Task(in *porch.Task, out *Task, s conversion.Scope) error {
	out.Type = TaskType(in.Type)
	out.Init = (*PorchPkgInitTaskSpec)(unsafe.Pointer(in.Init))
	out.Clone = (*PorchPkgCloneTaskSpec)(unsafe.Pointer(in.Clone))
	out.Patch = (*PorchPkgPatchTaskSpec)(unsafe.Pointer(in.Patch))
	out.Edit = (*PorchPkgEditTaskSpec)(unsafe.Pointer(in.Edit))
	out.Eval = (*FunctionEvalTaskSpec)(unsafe.Pointer(in.Eval))
	out.Update = (*PorchPkgUpdateTaskSpec)(unsafe.Pointer(in.Update))
	return nil
}

// Convert_porch_Task_To_v1alpha1_Task is an autogenerated conversion function.
func Convert_porch_Task_To_v1alpha1_Task(in *porch.Task, out *Task, s conversion.Scope) error {
	return autoConvert_porch_Task_To_v1alpha1_Task(in, out, s)
}

func autoConvert_v1alpha1_TaskResult_To_porch_TaskResult(in *TaskResult, out *porch.TaskResult, s conversion.Scope) error {
	out.Task = (*porch.Task)(unsafe.Pointer(in.Task))
	out.RenderStatus = (*porch.RenderStatus)(unsafe.Pointer(in.RenderStatus))
	return nil
}

// Convert_v1alpha1_TaskResult_To_porch_TaskResult is an autogenerated conversion function.
func Convert_v1alpha1_TaskResult_To_porch_TaskResult(in *TaskResult, out *porch.TaskResult, s conversion.Scope) error {
	return autoConvert_v1alpha1_TaskResult_To_porch_TaskResult(in, out, s)
}

func autoConvert_porch_TaskResult_To_v1alpha1_TaskResult(in *porch.TaskResult, out *TaskResult, s conversion.Scope) error {
	out.Task = (*Task)(unsafe.Pointer(in.Task))
	out.RenderStatus = (*RenderStatus)(unsafe.Pointer(in.RenderStatus))
	return nil
}

// Convert_porch_TaskResult_To_v1alpha1_TaskResult is an autogenerated conversion function.
func Convert_porch_TaskResult_To_v1alpha1_TaskResult(in *porch.TaskResult, out *TaskResult, s conversion.Scope) error {
	return autoConvert_porch_TaskResult_To_v1alpha1_TaskResult(in, out, s)
}

func autoConvert_v1alpha1_UpstreamLock_To_porch_UpstreamLock(in *UpstreamLock, out *porch.UpstreamLock, s conversion.Scope) error {
	out.Type = porch.OriginType(in.Type)
	out.Git = (*porch.GitLock)(unsafe.Pointer(in.Git))
	return nil
}

// Convert_v1alpha1_UpstreamLock_To_porch_UpstreamLock is an autogenerated conversion function.
func Convert_v1alpha1_UpstreamLock_To_porch_UpstreamLock(in *UpstreamLock, out *porch.UpstreamLock, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpstreamLock_To_porch_UpstreamLock(in, out, s)
}

func autoConvert_porch_UpstreamLock_To_v1alpha1_UpstreamLock(in *porch.UpstreamLock, out *UpstreamLock, s conversion.Scope) error {
	out.Type = OriginType(in.Type)
	out.Git = (*GitLock)(unsafe.Pointer(in.Git))
	return nil
}

// Convert_porch_UpstreamLock_To_v1alpha1_UpstreamLock is an autogenerated conversion function.
func Convert_porch_UpstreamLock_To_v1alpha1_UpstreamLock(in *porch.UpstreamLock, out *UpstreamLock, s conversion.Scope) error {
	return autoConvert_porch_UpstreamLock_To_v1alpha1_UpstreamLock(in, out, s)
}

func autoConvert_v1alpha1_UpstreamPorchPkg_To_porch_UpstreamPorchPkg(in *UpstreamPorchPkg, out *porch.UpstreamPorchPkg, s conversion.Scope) error {
	out.Type = porch.RepositoryType(in.Type)
	out.Git = (*porch.GitPorchPkg)(unsafe.Pointer(in.Git))
	out.Oci = (*porch.OciPorchPkg)(unsafe.Pointer(in.Oci))
	out.UpstreamRef = (*porch.PorchPkgRevisionRef)(unsafe.Pointer(in.UpstreamRef))
	return nil
}

// Convert_v1alpha1_UpstreamPorchPkg_To_porch_UpstreamPorchPkg is an autogenerated conversion function.
func Convert_v1alpha1_UpstreamPorchPkg_To_porch_UpstreamPorchPkg(in *UpstreamPorchPkg, out *porch.UpstreamPorchPkg, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpstreamPorchPkg_To_porch_UpstreamPorchPkg(in, out, s)
}

func autoConvert_porch_UpstreamPorchPkg_To_v1alpha1_UpstreamPorchPkg(in *porch.UpstreamPorchPkg, out *UpstreamPorchPkg, s conversion.Scope) error {
	out.Type = RepositoryType(in.Type)
	out.Git = (*GitPorchPkg)(unsafe.Pointer(in.Git))
	out.Oci = (*OciPorchPkg)(unsafe.Pointer(in.Oci))
	out.UpstreamRef = (*PorchPkgRevisionRef)(unsafe.Pointer(in.UpstreamRef))
	return nil
}

// Convert_porch_UpstreamPorchPkg_To_v1alpha1_UpstreamPorchPkg is an autogenerated conversion function.
func Convert_porch_UpstreamPorchPkg_To_v1alpha1_UpstreamPorchPkg(in *porch.UpstreamPorchPkg, out *UpstreamPorchPkg, s conversion.Scope) error {
	return autoConvert_porch_UpstreamPorchPkg_To_v1alpha1_UpstreamPorchPkg(in, out, s)
}
