// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbcache

import (
	"context"
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewMockdbSQLInterface creates a new instance of MockdbSQLInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdbSQLInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdbSQLInterface {
	mock := &MockdbSQLInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockdbSQLInterface is an autogenerated mock type for the dbSQLInterface type
type MockdbSQLInterface struct {
	mock.Mock
}

type MockdbSQLInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdbSQLInterface) EXPECT() *MockdbSQLInterface_Expecter {
	return &MockdbSQLInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockdbSQLInterface
func (_mock *MockdbSQLInterface) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockdbSQLInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockdbSQLInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockdbSQLInterface_Expecter) Close() *MockdbSQLInterface_Close_Call {
	return &MockdbSQLInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockdbSQLInterface_Close_Call) Run(run func()) *MockdbSQLInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockdbSQLInterface_Close_Call) Return(err error) *MockdbSQLInterface_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockdbSQLInterface_Close_Call) RunAndReturn(run func() error) *MockdbSQLInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function for the type MockdbSQLInterface
func (_mock *MockdbSQLInterface) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (sql.Result, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) sql.Result); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockdbSQLInterface_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockdbSQLInterface_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockdbSQLInterface_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *MockdbSQLInterface_ExecContext_Call {
	return &MockdbSQLInterface_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockdbSQLInterface_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockdbSQLInterface_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockdbSQLInterface_ExecContext_Call) Return(result sql.Result, err error) *MockdbSQLInterface_ExecContext_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockdbSQLInterface_ExecContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (sql.Result, error)) *MockdbSQLInterface_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function for the type MockdbSQLInterface
func (_mock *MockdbSQLInterface) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (*sql.Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockdbSQLInterface_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockdbSQLInterface_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockdbSQLInterface_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *MockdbSQLInterface_QueryContext_Call {
	return &MockdbSQLInterface_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockdbSQLInterface_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockdbSQLInterface_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockdbSQLInterface_QueryContext_Call) Return(rows *sql.Rows, err error) *MockdbSQLInterface_QueryContext_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockdbSQLInterface_QueryContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (*sql.Rows, error)) *MockdbSQLInterface_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function for the type MockdbSQLInterface
func (_mock *MockdbSQLInterface) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// MockdbSQLInterface_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type MockdbSQLInterface_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockdbSQLInterface_Expecter) QueryRowContext(ctx interface{}, query interface{}, args ...interface{}) *MockdbSQLInterface_QueryRowContext_Call {
	return &MockdbSQLInterface_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockdbSQLInterface_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockdbSQLInterface_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockdbSQLInterface_QueryRowContext_Call) Return(row *sql.Row) *MockdbSQLInterface_QueryRowContext_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockdbSQLInterface_QueryRowContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) *sql.Row) *MockdbSQLInterface_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}
