// Copyright 2022 The kpt and Nephio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: evaluator.proto

package evaluator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateFunctionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized ResourceList (https://kpt.dev/reference/schema/resource-list/)
	ResourceList []byte `protobuf:"bytes,1,opt,name=resource_list,json=resourceList,proto3" json:"resource_list,omitempty"`
	// kpt image identifying the function to evaluate
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// optional field for function description.
	Tag           string `protobuf:"bytes,3,opt,name=Tag,proto3" json:"Tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateFunctionRequest) Reset() {
	*x = EvaluateFunctionRequest{}
	mi := &file_evaluator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFunctionRequest) ProtoMessage() {}

func (x *EvaluateFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evaluator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFunctionRequest.ProtoReflect.Descriptor instead.
func (*EvaluateFunctionRequest) Descriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateFunctionRequest) GetResourceList() []byte {
	if x != nil {
		return x.ResourceList
	}
	return nil
}

func (x *EvaluateFunctionRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *EvaluateFunctionRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// ConfigMap wraps a map<string, string> for use in oneof clause.
type ConfigMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMap) Reset() {
	*x = ConfigMap{}
	mi := &file_evaluator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMap) ProtoMessage() {}

func (x *ConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_evaluator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMap.ProtoReflect.Descriptor instead.
func (*ConfigMap) Descriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigMap) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type EvaluateFunctionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized ResourceList (https://kpt.dev/reference/schema/resource-list/),
	// including structured function results.
	ResourceList []byte `protobuf:"bytes,1,opt,name=resource_list,json=resourceList,proto3" json:"resource_list,omitempty"`
	// Additional log produced by the function (if any).
	Log           []byte `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateFunctionResponse) Reset() {
	*x = EvaluateFunctionResponse{}
	mi := &file_evaluator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFunctionResponse) ProtoMessage() {}

func (x *EvaluateFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evaluator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFunctionResponse.ProtoReflect.Descriptor instead.
func (*EvaluateFunctionResponse) Descriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateFunctionResponse) GetResourceList() []byte {
	if x != nil {
		return x.ResourceList
	}
	return nil
}

func (x *EvaluateFunctionResponse) GetLog() []byte {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_evaluator_proto protoreflect.FileDescriptor

const file_evaluator_proto_rawDesc = "" +
	"\n" +
	"\x0fevaluator.proto\x12\tevaluator\x1a\fstruct.proto\"f\n" +
	"\x17EvaluateFunctionRequest\x12#\n" +
	"\rresource_list\x18\x01 \x01(\fR\fresourceList\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x10\n" +
	"\x03Tag\x18\x03 \x01(\tR\x03Tag\"x\n" +
	"\tConfigMap\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.evaluator.ConfigMap.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x18EvaluateFunctionResponse\x12#\n" +
	"\rresource_list\x18\x01 \x01(\fR\fresourceList\x12\x10\n" +
	"\x03log\x18\x02 \x01(\fR\x03log2r\n" +
	"\x11FunctionEvaluator\x12]\n" +
	"\x10EvaluateFunction\x12\".evaluator.EvaluateFunctionRequest\x1a#.evaluator.EvaluateFunctionResponse\"\x00B0Z.github.com/nephio-project/porch/func/evaluatorb\x06proto3"

var (
	file_evaluator_proto_rawDescOnce sync.Once
	file_evaluator_proto_rawDescData []byte
)

func file_evaluator_proto_rawDescGZIP() []byte {
	file_evaluator_proto_rawDescOnce.Do(func() {
		file_evaluator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evaluator_proto_rawDesc), len(file_evaluator_proto_rawDesc)))
	})
	return file_evaluator_proto_rawDescData
}

var file_evaluator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_evaluator_proto_goTypes = []any{
	(*EvaluateFunctionRequest)(nil),  // 0: evaluator.EvaluateFunctionRequest
	(*ConfigMap)(nil),                // 1: evaluator.ConfigMap
	(*EvaluateFunctionResponse)(nil), // 2: evaluator.EvaluateFunctionResponse
	nil,                              // 3: evaluator.ConfigMap.DataEntry
}
var file_evaluator_proto_depIdxs = []int32{
	3, // 0: evaluator.ConfigMap.data:type_name -> evaluator.ConfigMap.DataEntry
	0, // 1: evaluator.FunctionEvaluator.EvaluateFunction:input_type -> evaluator.EvaluateFunctionRequest
	2, // 2: evaluator.FunctionEvaluator.EvaluateFunction:output_type -> evaluator.EvaluateFunctionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_evaluator_proto_init() }
func file_evaluator_proto_init() {
	if File_evaluator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evaluator_proto_rawDesc), len(file_evaluator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evaluator_proto_goTypes,
		DependencyIndexes: file_evaluator_proto_depIdxs,
		MessageInfos:      file_evaluator_proto_msgTypes,
	}.Build()
	File_evaluator_proto = out.File
	file_evaluator_proto_goTypes = nil
	file_evaluator_proto_depIdxs = nil
}
