// Copyright 2022 The kpt and Nephio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: evaluator.proto

package evaluator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FunctionEvaluator_EvaluateFunction_FullMethodName = "/evaluator.FunctionEvaluator/EvaluateFunction"
)

// FunctionEvaluatorClient is the client API for FunctionEvaluator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Evaluator of kpt functions
type FunctionEvaluatorClient interface {
	// Evaluates a kpt function on the provided package
	EvaluateFunction(ctx context.Context, in *EvaluateFunctionRequest, opts ...grpc.CallOption) (*EvaluateFunctionResponse, error)
}

type functionEvaluatorClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionEvaluatorClient(cc grpc.ClientConnInterface) FunctionEvaluatorClient {
	return &functionEvaluatorClient{cc}
}

func (c *functionEvaluatorClient) EvaluateFunction(ctx context.Context, in *EvaluateFunctionRequest, opts ...grpc.CallOption) (*EvaluateFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateFunctionResponse)
	err := c.cc.Invoke(ctx, FunctionEvaluator_EvaluateFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionEvaluatorServer is the server API for FunctionEvaluator service.
// All implementations must embed UnimplementedFunctionEvaluatorServer
// for forward compatibility.
//
// Evaluator of kpt functions
type FunctionEvaluatorServer interface {
	// Evaluates a kpt function on the provided package
	EvaluateFunction(context.Context, *EvaluateFunctionRequest) (*EvaluateFunctionResponse, error)
	mustEmbedUnimplementedFunctionEvaluatorServer()
}

// UnimplementedFunctionEvaluatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFunctionEvaluatorServer struct{}

func (UnimplementedFunctionEvaluatorServer) EvaluateFunction(context.Context, *EvaluateFunctionRequest) (*EvaluateFunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateFunction not implemented")
}
func (UnimplementedFunctionEvaluatorServer) mustEmbedUnimplementedFunctionEvaluatorServer() {}
func (UnimplementedFunctionEvaluatorServer) testEmbeddedByValue()                           {}

// UnsafeFunctionEvaluatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionEvaluatorServer will
// result in compilation errors.
type UnsafeFunctionEvaluatorServer interface {
	mustEmbedUnimplementedFunctionEvaluatorServer()
}

func RegisterFunctionEvaluatorServer(s grpc.ServiceRegistrar, srv FunctionEvaluatorServer) {
	// If the following call panics, it indicates UnimplementedFunctionEvaluatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FunctionEvaluator_ServiceDesc, srv)
}

func _FunctionEvaluator_EvaluateFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionEvaluatorServer).EvaluateFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionEvaluator_EvaluateFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionEvaluatorServer).EvaluateFunction(ctx, req.(*EvaluateFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FunctionEvaluator_ServiceDesc is the grpc.ServiceDesc for FunctionEvaluator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunctionEvaluator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evaluator.FunctionEvaluator",
	HandlerType: (*FunctionEvaluatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateFunction",
			Handler:    _FunctionEvaluator_EvaluateFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evaluator.proto",
}
